-- [GENERATED BY AENEAS]
-- This file was automatically generated by Aeneas from the Rust crate `infix_calc`.
-- It contains the function definitions translated from Rust to pure Lean.
--
-- KEY OBSERVATIONS:
--
-- 1. The lexer's while loop becomes a `partial_fixpoint` recursive function
--    decorated with @[rust_loop]. The loop state (index, accumulated tokens)
--    is passed as parameters.
--
-- 2. The parser's while loops (in parse_expr and parse_term) similarly become
--    `partial_fixpoint` loops. parse_factor contains a recursive call to
--    parse_expr (for parenthesized sub-expressions), which Aeneas handles
--    via mutual recursion or fuel.
--
-- 3. The evaluator (eval) is structural recursion on Expr — no loops needed.
--    Each recursive call on a sub-expression is a direct `do`-notation bind.
--
-- 4. All functions return `Result T` (Aeneas wrapper). Functions that return
--    Rust's Result<A, B> produce `Result (core.result.Result A B)`.
--
-- DO NOT EDIT THIS FILE — it will be overwritten when you re-run Aeneas.

import Aeneas
import InfixCalc.Types

open Aeneas Aeneas.Std Result
open infix_calc

namespace infix_calc

-- ============================================================================
-- Lexer
-- ============================================================================

/-- Inner loop of the lexer. Processes one byte at a time, accumulating tokens.
    The while loop in Rust becomes this partial_fixpoint recursive function. -/
@[rust_loop]
partial_fixpoint def lex_loop
    (input : Vec U8) (i : Usize) (tokens : Vec Token)
    : Result (Vec Token) := do
  if h : i < input.len then do
    let ch ← input.index ⟨i, h⟩
    if ch = 32 ∨ ch = 9 ∨ ch = 10 ∨ ch = 13 then do
      -- Skip whitespace
      let i' ← i + (1 : Usize)
      lex_loop input i' tokens
    else if ch = 43 then do
      -- '+'
      let tokens' ← tokens.push (Token.Operator Op.Add)
      let i' ← i + (1 : Usize)
      lex_loop input i' tokens'
    else if ch = 45 then do
      -- '-' (treated as subtraction operator for simplicity)
      let tokens' ← tokens.push (Token.Operator Op.Sub)
      let i' ← i + (1 : Usize)
      lex_loop input i' tokens'
    else if ch = 42 then do
      -- '*'
      let tokens' ← tokens.push (Token.Operator Op.Mul)
      let i' ← i + (1 : Usize)
      lex_loop input i' tokens'
    else if ch = 47 then do
      -- '/'
      let tokens' ← tokens.push (Token.Operator Op.Div)
      let i' ← i + (1 : Usize)
      lex_loop input i' tokens'
    else if ch = 40 then do
      -- '('
      let tokens' ← tokens.push Token.LParen
      let i' ← i + (1 : Usize)
      lex_loop input i' tokens'
    else if ch = 41 then do
      -- ')'
      let tokens' ← tokens.push Token.RParen
      let i' ← i + (1 : Usize)
      lex_loop input i' tokens'
    else if 48 ≤ ch ∧ ch ≤ 57 then do
      -- Digit: parse multi-digit number
      let digit ← I64.ofU8 (ch - 48)
      let ⟨i', value⟩ ← lex_num_loop input (← i + (1 : Usize)) digit
      let tokens' ← tokens.push (Token.Num value)
      lex_loop input i' tokens'
    else
      .fail .panic  -- UnexpectedToken
  else
    ok tokens

/-- Inner loop for parsing a multi-digit number. -/
@[rust_loop]
partial_fixpoint def lex_num_loop
    (input : Vec U8) (i : Usize) (value : I64)
    : Result (Usize × I64) := do
  if h : i < input.len then do
    let ch ← input.index ⟨i, h⟩
    if 48 ≤ ch ∧ ch ≤ 57 then do
      let digit ← I64.ofU8 (ch - 48)
      let value' ← value * (10 : I64) + digit
      let i' ← i + (1 : Usize)
      lex_num_loop input i' value'
    else
      ok (i, value)
  else
    ok (i, value)

/-- Top-level lexer function.
    Rust: pub fn lex(input: &[u8]) -> Result<Vec<Token>, ParseError> -/
def lex (input : Vec U8) : Result (core.result.Result (Vec Token) ParseError) := do
  let tokens ← lex_loop input (0 : Usize) (Vec.new)
  ok (.ok tokens)

-- ============================================================================
-- Parser
-- ============================================================================

/-- Parse an atomic expression: number or parenthesized sub-expression.
    Rust: pub fn parse_factor(tokens: &[Token], pos: usize)
              -> Result<(Expr, usize), ParseError>

    Note: This calls parse_expr for parenthesized expressions,
    creating mutual recursion that Aeneas resolves. -/
partial_fixpoint def parse_factor
    (tokens : Vec Token) (pos : Usize)
    : Result (core.result.Result (Expr × Usize) ParseError) := do
  if h : pos < tokens.len then do
    let tok ← tokens.index ⟨pos, h⟩
    match tok with
    | Token.Num n => do
        let pos' ← pos + (1 : Usize)
        ok (.ok (Expr.Num n, pos'))
    | Token.LParen => do
        let pos1 ← pos + (1 : Usize)
        let inner ← parse_expr tokens pos1
        match inner with
        | .err e => ok (.err e)
        | .ok (expr, pos2) =>
          if h2 : pos2 < tokens.len then do
            let tok2 ← tokens.index ⟨pos2, h2⟩
            match tok2 with
            | Token.RParen => do
                let pos3 ← pos2 + (1 : Usize)
                ok (.ok (expr, pos3))
            | _ => ok (.err ParseError.UnexpectedToken)
          else
            ok (.err ParseError.UnexpectedEnd)
    | _ => ok (.err ParseError.UnexpectedToken)
  else
    ok (.err ParseError.UnexpectedEnd)

/-- Loop body for parse_term: handles * and / operators. -/
@[rust_loop]
partial_fixpoint def parse_term_loop
    (tokens : Vec Token) (left : Expr) (pos : Usize)
    : Result (core.result.Result (Expr × Usize) ParseError) := do
  if h : pos < tokens.len then do
    let tok ← tokens.index ⟨pos, h⟩
    match tok with
    | Token.Operator Op.Mul => do
        let pos1 ← pos + (1 : Usize)
        let right_result ← parse_factor tokens pos1
        match right_result with
        | .err e => ok (.err e)
        | .ok (right, pos2) =>
          parse_term_loop tokens (Expr.BinOp Op.Mul left right) pos2
    | Token.Operator Op.Div => do
        let pos1 ← pos + (1 : Usize)
        let right_result ← parse_factor tokens pos1
        match right_result with
        | .err e => ok (.err e)
        | .ok (right, pos2) =>
          parse_term_loop tokens (Expr.BinOp Op.Div left right) pos2
    | _ => ok (.ok (left, pos))
  else
    ok (.ok (left, pos))

/-- Parse a multiplicative expression: factor (('*' | '/') factor)*
    Rust: pub fn parse_term(tokens: &[Token], pos: usize)
              -> Result<(Expr, usize), ParseError> -/
def parse_term
    (tokens : Vec Token) (pos : Usize)
    : Result (core.result.Result (Expr × Usize) ParseError) := do
  let first ← parse_factor tokens pos
  match first with
  | .err e => ok (.err e)
  | .ok (left, pos1) => parse_term_loop tokens left pos1

/-- Loop body for parse_expr: handles + and - operators. -/
@[rust_loop]
partial_fixpoint def parse_expr_loop
    (tokens : Vec Token) (left : Expr) (pos : Usize)
    : Result (core.result.Result (Expr × Usize) ParseError) := do
  if h : pos < tokens.len then do
    let tok ← tokens.index ⟨pos, h⟩
    match tok with
    | Token.Operator Op.Add => do
        let pos1 ← pos + (1 : Usize)
        let right_result ← parse_term tokens pos1
        match right_result with
        | .err e => ok (.err e)
        | .ok (right, pos2) =>
          parse_expr_loop tokens (Expr.BinOp Op.Add left right) pos2
    | Token.Operator Op.Sub => do
        let pos1 ← pos + (1 : Usize)
        let right_result ← parse_term tokens pos1
        match right_result with
        | .err e => ok (.err e)
        | .ok (right, pos2) =>
          parse_expr_loop tokens (Expr.BinOp Op.Sub left right) pos2
    | _ => ok (.ok (left, pos))
  else
    ok (.ok (left, pos))

/-- Parse an additive expression: term (('+' | '-') term)*
    Rust: pub fn parse_expr(tokens: &[Token], pos: usize)
              -> Result<(Expr, usize), ParseError> -/
def parse_expr
    (tokens : Vec Token) (pos : Usize)
    : Result (core.result.Result (Expr × Usize) ParseError) := do
  let first ← parse_term tokens pos
  match first with
  | .err e => ok (.err e)
  | .ok (left, pos1) => parse_expr_loop tokens left pos1

/-- Top-level parse function. Checks that all tokens are consumed.
    Rust: pub fn parse(tokens: &[Token]) -> Result<Expr, ParseError> -/
def parse (tokens : Vec Token) : Result (core.result.Result Expr ParseError) := do
  let result ← parse_expr tokens (0 : Usize)
  match result with
  | .err e => ok (.err e)
  | .ok (expr, pos) =>
    if pos = tokens.len then
      ok (.ok expr)
    else
      ok (.err ParseError.TrailingTokens)

-- ============================================================================
-- Evaluator
-- ============================================================================

/-- Evaluate an expression tree. Structural recursion on Expr.
    Rust: pub fn eval(expr: &Expr) -> Result<i64, EvalError>

    This is the cleanest translation: Expr is an inductive type, and
    eval is defined by structural recursion — no loops, no fuel needed.
    Each match arm directly corresponds to a Rust match arm. -/
def eval (expr : Expr) : Result (core.result.Result I64 EvalError) := do
  match expr with
  | Expr.Num n => ok (.ok n)
  | Expr.BinOp op left right => do
    let lr ← eval left
    match lr with
    | .err e => ok (.err e)
    | .ok l => do
      let rr ← eval right
      match rr with
      | .err e => ok (.err e)
      | .ok r =>
        match op with
        | Op.Add => do
            let result ← l + r
            ok (.ok result)
        | Op.Sub => do
            let result ← l - r
            ok (.ok result)
        | Op.Mul => do
            let result ← l * r
            ok (.ok result)
        | Op.Div =>
          if r = (0 : I64) then
            ok (.err EvalError.DivisionByZero)
          else do
            let result ← l / r
            ok (.ok result)

end infix_calc
