-- [GENERATED BY AENEAS]
-- This file was automatically generated by Aeneas from the Rust crate `infix_calc`.
-- It contains the type definitions extracted from the Rust source.
--
-- Key observation: Box<Expr> in Rust becomes just Expr in Lean.
-- Aeneas erases the heap indirection — the recursive enum becomes a
-- straightforward Lean inductive type.
--
-- DO NOT EDIT THIS FILE — it will be overwritten when you re-run Aeneas.

import Aeneas
open Aeneas Aeneas.Std

namespace infix_calc

/-- Binary operators with standard arithmetic precedence. -/
inductive Op where
  | Add : Op
  | Sub : Op
  | Mul : Op
  | Div : Op
deriving Inhabited, DecidableEq

/-- Lexer tokens for infix expressions. -/
inductive Token where
  | Num : I64 → Token
  | Operator : Op → Token
  | LParen : Token
  | RParen : Token
deriving Inhabited, DecidableEq

/-- Abstract syntax tree for arithmetic expressions.
    Note: Box<Expr> in Rust becomes plain Expr here — Aeneas erases
    the heap indirection, producing a clean recursive type. -/
inductive Expr where
  | Num : I64 → Expr
  | BinOp : Op → Expr → Expr → Expr
deriving Inhabited, DecidableEq

/-- Parser error variants. -/
inductive ParseError where
  | UnexpectedToken : ParseError
  | UnexpectedEnd : ParseError
  | TrailingTokens : ParseError
deriving Inhabited, DecidableEq

/-- Evaluator error variants. -/
inductive EvalError where
  | DivisionByZero : EvalError
  | Overflow : EvalError
deriving Inhabited, DecidableEq

end infix_calc
