-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rpn_calc]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace rpn_calc

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field2_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2620:4-2625:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field2_finish] -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field2_finish"]
axiom core.fmt.Formatter.debug_tuple_field2_finish
  :
  core.fmt.Formatter → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Dyn
    (fun _dyn => core.fmt.Debug _dyn) → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::ops::range::RangeInclusive]
    Source: '/rustc/library/core/src/ops/range.rs', lines 357:0-357:30
    Name pattern: [core::ops::range::RangeInclusive] -/
@[rust_type "core::ops::range::RangeInclusive"]
axiom core.ops.range.RangeInclusive (Idx : Type) : Type

/-- [core::ops::range::{core::ops::range::RangeInclusive<Idx>}::new]:
    Source: '/rustc/library/core/src/ops/range.rs', lines 390:4-390:50
    Name pattern: [core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::new] -/
@[rust_fun "core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::new"]
axiom core.ops.range.RangeInclusive.new
  {Idx : Type} : Idx → Idx → Result (core.ops.range.RangeInclusive Idx)

/-- [core::ops::range::{core::ops::range::RangeInclusive<Idx>}::contains]:
    Source: '/rustc/library/core/src/ops/range.rs', lines 522:4-525:44
    Name pattern: [core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::contains] -/
@[rust_fun
  "core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::contains"]
axiom core.ops.range.RangeInclusive.contains
  {Idx : Type} {U : Type} (cmpPartialOrdInst : core.cmp.PartialOrd Idx Idx)
  (cmpPartialOrdInst1 : core.cmp.PartialOrd Idx U) (cmpPartialOrdInst2 :
  core.cmp.PartialOrd U Idx) :
  core.ops.range.RangeInclusive Idx → U → Result Bool

/-- [core::result::{core::ops::try_trait::Try<T, core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2172:4-2172:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch] -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch"]
axiom core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
  {T : Type} {E : Type} :
  core.result.Result T E → Result (core.ops.control_flow.ControlFlow
    (core.result.Result core.convert.Infallible E) T)

/-- [core::result::{core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2187:4-2187:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual] -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
axiom
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
  (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
  core.result.Result core.convert.Infallible E → Result (core.result.Result T
    F)

/-- [alloc::boxed::{core::fmt::Debug for alloc::boxed::Box<T>}::fmt]:
    Source: '/rustc/library/alloc/src/boxed.rs', lines 2164:4-2164:60
    Name pattern: [alloc::boxed::{core::fmt::Debug<Box<@T>>}::fmt] -/
@[rust_fun "alloc::boxed::{core::fmt::Debug<Box<@T>>}::fmt"]
axiom Box.Insts.CoreFmtDebug.fmt
  {T : Type} (A : Type) (corefmtDebugInst : core.fmt.Debug T) :
  T → core.fmt.Formatter → Result ((core.result.Result Unit core.fmt.Error)
    × core.fmt.Formatter)

/-- Trait implementation: [alloc::boxed::{core::fmt::Debug for alloc::boxed::Box<T>}]
    Source: '/rustc/library/alloc/src/boxed.rs', lines 2163:0-2163:67
    Name pattern: [core::fmt::Debug<Box<@T>>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<Box<@T>>"]
def Box.Insts.CoreFmtDebug {T : Type} (A : Type) (corefmtDebugInst :
  core.fmt.Debug T) : core.fmt.Debug T := {
  fmt := Box.Insts.CoreFmtDebug.fmt A corefmtDebugInst
}

/-- [rpn_calc::Token]
    Source: 'src/lib.rs', lines 9:0-15:1 -/
@[discriminant isize]
inductive Token where
| Num : Std.I64 → Token
| Plus : Token
| Minus : Token
| Mul : Token
| Div : Token

/-- [rpn_calc::{core::clone::Clone for rpn_calc::Token}::clone]:
    Source: 'src/lib.rs', lines 8:9-8:14 -/
def Token.Insts.CoreCloneClone.clone (self : Token) : Result Token := do
  match self with
  | Token.Num __self_0 =>
    let i ← lift (core.clone.impls.CloneI64.clone __self_0)
    ok (Token.Num i)
  | Token.Plus => ok Token.Plus
  | Token.Minus => ok Token.Minus
  | Token.Mul => ok Token.Mul
  | Token.Div => ok Token.Div

/-- Trait implementation: [rpn_calc::{core::clone::Clone for rpn_calc::Token}]
    Source: 'src/lib.rs', lines 8:9-8:14 -/
@[reducible]
def Token.Insts.CoreCloneClone : core.clone.Clone Token := {
  clone := Token.Insts.CoreCloneClone.clone
}

/-- [rpn_calc::{core::fmt::Debug for rpn_calc::Token}::fmt]:
    Source: 'src/lib.rs', lines 8:16-8:21 -/
def Token.Insts.CoreFmtDebug.fmt
  (self : Token) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | Token.Num __self_0 =>
    let __self_01 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugI64) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Num") __self_01
  | Token.Plus => core.fmt.Formatter.write_str f (toStr "Plus")
  | Token.Minus => core.fmt.Formatter.write_str f (toStr "Minus")
  | Token.Mul => core.fmt.Formatter.write_str f (toStr "Mul")
  | Token.Div => core.fmt.Formatter.write_str f (toStr "Div")

/-- Trait implementation: [rpn_calc::{core::fmt::Debug for rpn_calc::Token}]
    Source: 'src/lib.rs', lines 8:16-8:21 -/
@[reducible]
def Token.Insts.CoreFmtDebug : core.fmt.Debug Token := {
  fmt := Token.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rpn_calc::{core::marker::StructuralPartialEq for rpn_calc::Token}]
    Source: 'src/lib.rs', lines 8:23-8:32 -/
@[reducible]
def Token.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Token := {
}

/-- [rpn_calc::{core::cmp::PartialEq<rpn_calc::Token> for rpn_calc::Token}::eq]:
    Source: 'src/lib.rs', lines 8:23-8:32 -/
def Token.Insts.CoreCmpPartialEqToken.eq
  (self : Token) (other : Token) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | Token.Num __self_0 =>
      match other with
      | Token.Num __arg1_0 =>
        lift (core.cmp.impls.PartialEqI64.eq __self_0 __arg1_0)
      | Token.Plus => ok true
      | Token.Minus => ok true
      | Token.Mul => ok true
      | Token.Div => ok true
    | Token.Plus => ok true
    | Token.Minus => ok true
    | Token.Mul => ok true
    | Token.Div => ok true
  else ok false

/-- Trait implementation: [rpn_calc::{core::cmp::PartialEq<rpn_calc::Token> for rpn_calc::Token}]
    Source: 'src/lib.rs', lines 8:23-8:32 -/
@[reducible]
def Token.Insts.CoreCmpPartialEqToken : core.cmp.PartialEq Token Token := {
  eq := Token.Insts.CoreCmpPartialEqToken.eq
}

/-- [rpn_calc::EvalError]
    Source: 'src/lib.rs', lines 19:0-24:1 -/
@[discriminant isize]
inductive EvalError where
| DivisionByZero : EvalError
| StackUnderflow : EvalError
| TooManyValues : EvalError
| InvalidToken : EvalError

/-- [rpn_calc::{core::clone::Clone for rpn_calc::EvalError}::clone]:
    Source: 'src/lib.rs', lines 18:9-18:14 -/
def EvalError.Insts.CoreCloneClone.clone
  (self : EvalError) : Result EvalError := do
  match self with
  | EvalError.DivisionByZero => ok EvalError.DivisionByZero
  | EvalError.StackUnderflow => ok EvalError.StackUnderflow
  | EvalError.TooManyValues => ok EvalError.TooManyValues
  | EvalError.InvalidToken => ok EvalError.InvalidToken

/-- Trait implementation: [rpn_calc::{core::clone::Clone for rpn_calc::EvalError}]
    Source: 'src/lib.rs', lines 18:9-18:14 -/
@[reducible]
def EvalError.Insts.CoreCloneClone : core.clone.Clone EvalError := {
  clone := EvalError.Insts.CoreCloneClone.clone
}

/-- [rpn_calc::{core::fmt::Debug for rpn_calc::EvalError}::fmt]:
    Source: 'src/lib.rs', lines 18:16-18:21 -/
def EvalError.Insts.CoreFmtDebug.fmt
  (self : EvalError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | EvalError.DivisionByZero =>
    core.fmt.Formatter.write_str f (toStr "DivisionByZero")
  | EvalError.StackUnderflow =>
    core.fmt.Formatter.write_str f (toStr "StackUnderflow")
  | EvalError.TooManyValues =>
    core.fmt.Formatter.write_str f (toStr "TooManyValues")
  | EvalError.InvalidToken =>
    core.fmt.Formatter.write_str f (toStr "InvalidToken")

/-- Trait implementation: [rpn_calc::{core::fmt::Debug for rpn_calc::EvalError}]
    Source: 'src/lib.rs', lines 18:16-18:21 -/
@[reducible]
def EvalError.Insts.CoreFmtDebug : core.fmt.Debug EvalError := {
  fmt := EvalError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rpn_calc::{core::marker::StructuralPartialEq for rpn_calc::EvalError}]
    Source: 'src/lib.rs', lines 18:23-18:32 -/
@[reducible]
def EvalError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq EvalError := {
}

/-- [rpn_calc::{core::cmp::PartialEq<rpn_calc::EvalError> for rpn_calc::EvalError}::eq]:
    Source: 'src/lib.rs', lines 18:23-18:32 -/
def EvalError.Insts.CoreCmpPartialEqEvalError.eq
  (self : EvalError) (other : EvalError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [rpn_calc::{core::cmp::PartialEq<rpn_calc::EvalError> for rpn_calc::EvalError}]
    Source: 'src/lib.rs', lines 18:23-18:32 -/
@[reducible]
def EvalError.Insts.CoreCmpPartialEqEvalError : core.cmp.PartialEq EvalError
  EvalError := {
  eq := EvalError.Insts.CoreCmpPartialEqEvalError.eq
}

/-- [rpn_calc::Stack]
    Source: 'src/lib.rs', lines 31:0-34:1 -/
@[discriminant isize]
inductive Stack where
| Empty : Stack
| Push : Std.I64 → Stack → Stack

/-- [rpn_calc::{core::clone::Clone for rpn_calc::Stack}::clone]:
    Source: 'src/lib.rs', lines 30:9-30:14 -/
def Stack.Insts.CoreCloneClone.clone (self : Stack) : Result Stack := do
  match self with
  | Stack.Empty => ok Stack.Empty
  | Stack.Push __self_0 __self_1 =>
    let i ← lift (core.clone.impls.CloneI64.clone __self_0)
    let s ← Stack.Insts.CoreCloneClone.clone __self_1
    ok (Stack.Push i s)
partial_fixpoint

/-- Trait implementation: [rpn_calc::{core::clone::Clone for rpn_calc::Stack}]
    Source: 'src/lib.rs', lines 30:9-30:14 -/
@[reducible]
def Stack.Insts.CoreCloneClone : core.clone.Clone Stack := {
  clone := Stack.Insts.CoreCloneClone.clone
}

/-- [rpn_calc::{core::fmt::Debug for rpn_calc::Stack}::fmt]:
    Source: 'src/lib.rs', lines 30:16-30:21 -/
def Stack.Insts.CoreFmtDebug.fmt
  (self : Stack) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | Stack.Empty => core.fmt.Formatter.write_str f (toStr "Empty")
  | Stack.Push __self_0 __self_1 =>
    let __self_01 := Dyn.mk _ core.fmt.DebugI64 __self_0
    let __self_11 :=
      Dyn.mk _ (core.fmt.DebugShared (Box.Insts.CoreFmtDebug Global
        Stack.Insts.CoreFmtDebug)) __self_1
    core.fmt.Formatter.debug_tuple_field2_finish f (toStr "Push") __self_01
      __self_11

/-- Trait implementation: [rpn_calc::{core::fmt::Debug for rpn_calc::Stack}]
    Source: 'src/lib.rs', lines 30:16-30:21 -/
@[reducible]
def Stack.Insts.CoreFmtDebug : core.fmt.Debug Stack := {
  fmt := Stack.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rpn_calc::{core::marker::StructuralPartialEq for rpn_calc::Stack}]
    Source: 'src/lib.rs', lines 30:23-30:32 -/
@[reducible]
def Stack.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Stack := {
}

/-- [rpn_calc::{core::cmp::PartialEq<rpn_calc::Stack> for rpn_calc::Stack}::eq]:
    Source: 'src/lib.rs', lines 30:23-30:32 -/
def Stack.Insts.CoreCmpPartialEqStack.eq
  (self : Stack) (other : Stack) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | Stack.Empty => ok true
    | Stack.Push __self_0 __self_1 =>
      match other with
      | Stack.Empty => ok true
      | Stack.Push __arg1_0 __arg1_1 =>
        let b ← lift (core.cmp.impls.PartialEqI64.eq __self_0 __arg1_0)
        if b
        then Stack.Insts.CoreCmpPartialEqStack.eq __self_1 __arg1_1
        else ok false
  else ok false
partial_fixpoint

/-- Trait implementation: [rpn_calc::{core::cmp::PartialEq<rpn_calc::Stack> for rpn_calc::Stack}]
    Source: 'src/lib.rs', lines 30:23-30:32 -/
@[reducible]
def Stack.Insts.CoreCmpPartialEqStack : core.cmp.PartialEq Stack Stack := {
  eq := Stack.Insts.CoreCmpPartialEqStack.eq
}

/-- [rpn_calc::{rpn_calc::Stack}::new]:
    Source: 'src/lib.rs', lines 38:4-40:5 -/
def Stack.new : Result Stack := do
  ok Stack.Empty

/-- [rpn_calc::{rpn_calc::Stack}::push]:
    Source: 'src/lib.rs', lines 43:4-45:5 -/
def Stack.push (self : Stack) (val : Std.I64) : Result Stack := do
  ok (Stack.Push val self)

/-- [rpn_calc::{rpn_calc::Stack}::pop]:
    Source: 'src/lib.rs', lines 49:4-54:5 -/
def Stack.pop
  (self : Stack) :
  Result (core.result.Result (Std.I64 × Stack) EvalError)
  := do
  match self with
  | Stack.Empty => ok (core.result.Result.Err EvalError.StackUnderflow)
  | Stack.Push val rest => ok (core.result.Result.Ok (val, rest))

/-- [rpn_calc::{rpn_calc::Stack}::peek]:
    Source: 'src/lib.rs', lines 57:4-62:5 -/
def Stack.peek
  (self : Stack) : Result (core.result.Result Std.I64 EvalError) := do
  match self with
  | Stack.Empty => ok (core.result.Result.Err EvalError.StackUnderflow)
  | Stack.Push val _ => ok (core.result.Result.Ok val)

/-- [rpn_calc::{rpn_calc::Stack}::len]:
    Source: 'src/lib.rs', lines 65:4-70:5 -/
def Stack.len (self : Stack) : Result Std.Usize := do
  match self with
  | Stack.Empty => ok 0#usize
  | Stack.Push _ rest => let i ← Stack.len rest
                         1#usize + i
partial_fixpoint

/-- [rpn_calc::{rpn_calc::Stack}::is_empty]:
    Source: 'src/lib.rs', lines 73:4-75:5 -/
def Stack.is_empty (self : Stack) : Result Bool := do
  match self with
  | Stack.Empty => ok true
  | Stack.Push _ _ => ok false

/-- [rpn_calc::parse_number]: loop body 0:
    Source: 'src/lib.rs', lines 0:0-117:1 -/
@[rust_loop_body]
def parse_number_loop.body
  (bytes : Slice Std.U8) (acc : Std.I64) (i : Std.Usize) :
  Result (ControlFlow (Std.I64 × Std.Usize) (core.result.Result Token
    EvalError))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let ri ← core.ops.range.RangeInclusive.new 48#u8 57#u8
    let c ← Slice.index_usize bytes i
    let b ←
      core.ops.range.RangeInclusive.contains core.cmp.PartialOrdU8
        core.cmp.PartialOrdU8 core.cmp.PartialOrdU8 ri c
    if b
    then
      let i2 ← acc * 10#i64
      let i3 ← c - 48#u8
      let i4 ← lift (UScalar.hcast .I64 i3)
      let acc1 ← i2 + i4
      let i5 ← i + 1#usize
      ok (cont (acc1, i5))
    else ok (done (core.result.Result.Err EvalError.InvalidToken))
  else ok (done (core.result.Result.Ok (Token.Num acc)))

/-- [rpn_calc::parse_number]: loop 0:
    Source: 'src/lib.rs', lines 0:0-117:1 -/
@[rust_loop]
def parse_number_loop
  (bytes : Slice Std.U8) (acc : Std.I64) (i : Std.Usize) :
  Result (core.result.Result Token EvalError)
  := do
  loop
    (fun (acc1, i1) => parse_number_loop.body bytes acc1 i1)
    (acc, i)

/-- [rpn_calc::parse_number]:
    Source: 'src/lib.rs', lines 102:0-117:1 -/
def parse_number
  (bytes : Slice Std.U8) : Result (core.result.Result Token EvalError) := do
  let b ← core.slice.Slice.is_empty bytes
  if b
  then ok (core.result.Result.Err EvalError.InvalidToken)
  else parse_number_loop bytes 0#i64 0#usize

/-- [rpn_calc::tokenize_word]:
    Source: 'src/lib.rs', lines 83:0-95:1 -/
def tokenize_word
  (word : Slice Std.U8) : Result (core.result.Result Token EvalError) := do
  let i := Slice.len word
  if i = 1#usize
  then
    let i1 ← Slice.index_usize word 0#usize
    match i1 with
    | 43#uscalar => ok (core.result.Result.Ok Token.Plus)
    | 45#uscalar => ok (core.result.Result.Ok Token.Minus)
    | 42#uscalar => ok (core.result.Result.Ok Token.Mul)
    | 47#uscalar => ok (core.result.Result.Ok Token.Div)
    | _ =>
      let ri ← core.ops.range.RangeInclusive.new 48#u8 57#u8
      let b ←
        core.ops.range.RangeInclusive.contains core.cmp.PartialOrdU8
          core.cmp.PartialOrdU8 core.cmp.PartialOrdU8 ri i1
      if b
      then
        let i2 ← i1 - 48#u8
        let i3 ← lift (UScalar.hcast .I64 i2)
        ok (core.result.Result.Ok (Token.Num i3))
      else ok (core.result.Result.Err EvalError.InvalidToken)
  else parse_number word

/-- [rpn_calc::apply_binop]:
    Source: 'src/lib.rs', lines 123:0-137:1 -/
def apply_binop
  (op : Token) (a : Std.I64) (b : Std.I64) :
  Result (core.result.Result Std.I64 EvalError)
  := do
  match op with
  | Token.Num _ => ok (core.result.Result.Err EvalError.InvalidToken)
  | Token.Plus => let i ← a + b
                  ok (core.result.Result.Ok i)
  | Token.Minus => let i ← a - b
                   ok (core.result.Result.Ok i)
  | Token.Mul => let i ← a * b
                 ok (core.result.Result.Ok i)
  | Token.Div =>
    if b = 0#i64
    then ok (core.result.Result.Err EvalError.DivisionByZero)
    else let i ← a / b
         ok (core.result.Result.Ok i)

/-- [rpn_calc::eval_step]:
    Source: 'src/lib.rs', lines 143:0-153:1 -/
def eval_step
  (stack : Stack) (token : Token) :
  Result (core.result.Result Stack EvalError)
  := do
  match token with
  | Token.Num n => let s ← Stack.push stack n
                   ok (core.result.Result.Ok s)
  | Token.Plus =>
    let r ← Stack.pop stack
    let cf ←
      core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let (b, stack1) := val
      let r1 ← Stack.pop stack1
      let cf1 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let (a, stack2) := val1
        let r2 ← apply_binop Token.Plus a b
        let cf2 ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r2
        match cf2 with
        | core.ops.control_flow.ControlFlow.Continue val2 =>
          let s ← Stack.push stack2 val2
          ok (core.result.Result.Ok s)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            Stack (core.convert.FromSame EvalError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          Stack (core.convert.FromSame EvalError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Stack (core.convert.FromSame EvalError) residual
  | Token.Minus =>
    let r ← Stack.pop stack
    let cf ←
      core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let (b, stack1) := val
      let r1 ← Stack.pop stack1
      let cf1 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let (a, stack2) := val1
        let r2 ← apply_binop Token.Minus a b
        let cf2 ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r2
        match cf2 with
        | core.ops.control_flow.ControlFlow.Continue val2 =>
          let s ← Stack.push stack2 val2
          ok (core.result.Result.Ok s)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            Stack (core.convert.FromSame EvalError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          Stack (core.convert.FromSame EvalError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Stack (core.convert.FromSame EvalError) residual
  | Token.Mul =>
    let r ← Stack.pop stack
    let cf ←
      core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let (b, stack1) := val
      let r1 ← Stack.pop stack1
      let cf1 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let (a, stack2) := val1
        let r2 ← apply_binop Token.Mul a b
        let cf2 ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r2
        match cf2 with
        | core.ops.control_flow.ControlFlow.Continue val2 =>
          let s ← Stack.push stack2 val2
          ok (core.result.Result.Ok s)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            Stack (core.convert.FromSame EvalError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          Stack (core.convert.FromSame EvalError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Stack (core.convert.FromSame EvalError) residual
  | Token.Div =>
    let r ← Stack.pop stack
    let cf ←
      core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let (b, stack1) := val
      let r1 ← Stack.pop stack1
      let cf1 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let (a, stack2) := val1
        let r2 ← apply_binop Token.Div a b
        let cf2 ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r2
        match cf2 with
        | core.ops.control_flow.ControlFlow.Continue val2 =>
          let s ← Stack.push stack2 val2
          ok (core.result.Result.Ok s)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            Stack (core.convert.FromSame EvalError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          Stack (core.convert.FromSame EvalError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Stack (core.convert.FromSame EvalError) residual

/-- [rpn_calc::evaluate]: loop body 0:
    Source: 'src/lib.rs', lines 162:4-171:1 -/
@[rust_loop_body]
def evaluate_loop.body
  (tokens : Slice Token) (stack : Stack) (i : Std.Usize) :
  Result (ControlFlow (Stack × Std.Usize) (core.result.Result Std.I64
    EvalError))
  := do
  let i1 := Slice.len tokens
  if i < i1
  then
    let t ← Slice.index_usize tokens i
    let r ← eval_step stack t
    let cf ←
      core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let i2 ← i + 1#usize
      ok (cont (val, i2))
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          Std.I64 (core.convert.FromSame EvalError) residual
      ok (done r1)
  else
    match stack with
    | Stack.Empty =>
      ok (done (core.result.Result.Err EvalError.StackUnderflow))
    | Stack.Push val rest =>
      let b ← Stack.is_empty rest
      if b
      then ok (done (core.result.Result.Ok val))
      else ok (done (core.result.Result.Err EvalError.TooManyValues))

/-- [rpn_calc::evaluate]: loop 0:
    Source: 'src/lib.rs', lines 162:4-171:1 -/
@[rust_loop]
def evaluate_loop
  (tokens : Slice Token) (stack : Stack) (i : Std.Usize) :
  Result (core.result.Result Std.I64 EvalError)
  := do
  loop
    (fun (stack1, i1) => evaluate_loop.body tokens stack1 i1)
    (stack, i)

/-- [rpn_calc::evaluate]:
    Source: 'src/lib.rs', lines 159:0-171:1 -/
def evaluate
  (tokens : Slice Token) : Result (core.result.Result Std.I64 EvalError) := do
  let stack ← Stack.new
  evaluate_loop tokens stack 0#usize

end rpn_calc
