-- [GENERATED BY AENEAS]
-- This file was automatically generated by Aeneas from the Rust crate `hello_proof`.
-- It contains the function definitions translated from Rust to pure Lean.
--
-- KEY CONCEPTS TO UNDERSTAND:
--
-- 1. Every function returns `Result T` where `T` is the Lean translation of
--    the Rust return type. The outer `Result` captures potential panics or
--    arithmetic overflow. If the Rust function itself returns `Result<A, B>`,
--    you get `Result (core.result.Result A B)` — a Result inside a Result.
--
-- 2. The `do` notation sequences operations that might fail. Each `let x ← expr`
--    line says "evaluate expr; if it fails, propagate the failure; otherwise
--    bind the result to x and continue."
--
-- 3. Arithmetic operations like `x + y` on bounded integers (U32, I64, etc.)
--    return `Result` because they can overflow. Aeneas's `+` is NOT the
--    mathematical `+` — it checks bounds and returns `fail` on overflow.
--
-- 4. The `↑` symbol (coercion) lifts a bounded integer to a mathematical
--    integer (Int or Nat) for reasoning purposes.
--
-- DO NOT EDIT THIS FILE — it will be overwritten when you re-run Aeneas.

import Aeneas
open Aeneas Aeneas.Std Result

namespace hello_proof

/-- Translation of `checked_add`.

    Rust:  pub fn checked_add(x: u32, y: u32) -> Option<u32>
    Lean:  The outer Result is Aeneas's wrapper (always ok here).
           The inner Option is Rust's Option<u32>.

    Note how Aeneas translates the overflow check:
    - `U32.MAX - x` can fail if x > MAX (impossible for U32, but Aeneas is conservative)
    - `x + y` can fail on overflow, but we only reach it when y <= MAX - x
-/
def checked_add (x : U32) (y : U32) : Result (Option U32) := do
  let max_minus_x ← U32.MAX - x
  if y ≤ max_minus_x then do
    let sum ← x + y
    ok (some sum)
  else
    ok none

/-- Translation of `safe_divide`.

    Rust:  pub fn safe_divide(x: i64, y: i64) -> Result<i64, ()>
    Lean:  Returns Result (core.result.Result I64 Unit)
           - Outer Result: Aeneas wrapper (fail on panic/overflow)
           - Inner Result: Rust's Result<i64, ()>
              .ok = division succeeded
              .err = division by zero

    Note: `x / y` on I64 can fail if x = I64.MIN and y = -1 (overflow).
    Aeneas's division checks this automatically.
-/
def safe_divide (x : I64) (y : I64) : Result (core.result.Result I64 Unit) := do
  if y = (0 : I64) then
    ok (.err ())
  else do
    let result ← x / y
    ok (.ok result)

/-- Translation of `safe_abs`.

    Rust:  pub fn safe_abs(x: i64) -> Result<i64, ()>
    Lean:  The I64.MIN check prevents the `-x` overflow case.
-/
def safe_abs (x : I64) : Result (core.result.Result I64 Unit) := do
  if x = I64.MIN then
    ok (.err ())
  else if x < (0 : I64) then do
    let neg_x ← -x
    ok (.ok neg_x)
  else
    ok (.ok x)

/-- Translation of `clamp`.

    Rust:  pub fn clamp(x: i32, lo: i32, hi: i32) -> i32
    Lean:  Pure function — no arithmetic operations that can fail.
           Only comparisons, which are total on I32.
           The outer Result is always `ok`.
-/
def clamp (x : I32) (lo : I32) (hi : I32) : Result I32 :=
  if x < lo then
    ok lo
  else if x > hi then
    ok hi
  else
    ok x

/-- Translation of `max_of`. Exercise function. -/
def max_of (a : I32) (b : I32) : Result I32 :=
  if a ≥ b then
    ok a
  else
    ok b

/-- Translation of `min_of`. Exercise function. -/
def min_of (a : I32) (b : I32) : Result I32 :=
  if a ≤ b then
    ok a
  else
    ok b

end hello_proof
