-- [GENERATED BY AENEAS]
-- This file was automatically generated by Aeneas from the Rust crate `hello_proof`.
-- It contains the type definitions extracted from the Rust source.
--
-- In this tutorial, the Rust code has no custom types (only primitive types
-- like u32, i32, i64 and standard types like Option and Result), so this
-- file is minimal. In later tutorials, your Rust enums and structs will
-- appear here as Lean `inductive` and `structure` types.
--
-- DO NOT EDIT THIS FILE — it will be overwritten when you re-run Aeneas.

import Aeneas
open Aeneas Aeneas.Std

namespace hello_proof

-- No custom types in this crate.
-- Primitive types (U32, I32, I64) come from the Aeneas standard library.
-- Option and Result are mapped to Lean's built-in Option and core.result.Result.

end hello_proof
