-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [buffer_management]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace buffer_management

/-- [buffer_management::gap_buffer::GapBuffer]
    Source: 'src/gap_buffer.rs', lines 16:0-20:1 -/
structure gap_buffer.GapBuffer where
  buffer : alloc.vec.Vec Std.U8
  gap_start : Std.Usize
  gap_end : Std.Usize

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::new]: loop body 0:
    Source: 'src/gap_buffer.rs', lines 29:8-32:9 -/
@[rust_loop_body]
def gap_buffer.GapBuffer.new_loop.body
  (capacity : Std.Usize) (buffer : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i < capacity
  then
    let buffer1 ← alloc.vec.Vec.push buffer 0#u8
    let i1 ← i + 1#usize
    ok (cont (buffer1, i1))
  else ok (done buffer)

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::new]: loop 0:
    Source: 'src/gap_buffer.rs', lines 29:8-32:9 -/
@[rust_loop]
def gap_buffer.GapBuffer.new_loop
  (capacity : Std.Usize) (buffer : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (buffer1, i1) => gap_buffer.GapBuffer.new_loop.body capacity buffer1
      i1)
    (buffer, i)

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::new]:
    Source: 'src/gap_buffer.rs', lines 26:4-38:5 -/
def gap_buffer.GapBuffer.new
  (capacity : Std.Usize) : Result gap_buffer.GapBuffer := do
  let buffer ←
    gap_buffer.GapBuffer.new_loop capacity (alloc.vec.Vec.new Std.U8) 0#usize
  ok { buffer, gap_start := 0#usize, gap_end := capacity }

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::insert]:
    Source: 'src/gap_buffer.rs', lines 44:4-51:5 -/
def gap_buffer.GapBuffer.insert
  (self : gap_buffer.GapBuffer) (ch : Std.U8) :
  Result gap_buffer.GapBuffer
  := do
  if self.gap_start = self.gap_end
  then ok self
  else
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.U8)
        self.buffer self.gap_start
    let i ← self.gap_start + 1#usize
    let v := index_mut_back ch
    ok { self with buffer := v, gap_start := i }

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::delete_before]:
    Source: 'src/gap_buffer.rs', lines 57:4-63:5 -/
def gap_buffer.GapBuffer.delete_before
  (self : gap_buffer.GapBuffer) : Result (Bool × gap_buffer.GapBuffer) := do
  if self.gap_start = 0#usize
  then ok (false, self)
  else
    let i ← self.gap_start - 1#usize
    ok (true, { self with gap_start := i })

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::delete_after]:
    Source: 'src/gap_buffer.rs', lines 69:4-75:5 -/
def gap_buffer.GapBuffer.delete_after
  (self : gap_buffer.GapBuffer) : Result (Bool × gap_buffer.GapBuffer) := do
  let i := alloc.vec.Vec.len self.buffer
  if self.gap_end = i
  then ok (false, self)
  else let i1 ← self.gap_end + 1#usize
       ok (true, { self with gap_end := i1 })

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::move_left]:
    Source: 'src/gap_buffer.rs', lines 81:4-89:5 -/
def gap_buffer.GapBuffer.move_left
  (self : gap_buffer.GapBuffer) : Result (Bool × gap_buffer.GapBuffer) := do
  if self.gap_start = 0#usize
  then ok (false, self)
  else
    let i ← self.gap_end - 1#usize
    let i1 ← self.gap_start - 1#usize
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8)
        self.buffer i1
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.U8)
        self.buffer i
    let v := index_mut_back i2
    ok (true, { buffer := v, gap_start := i1, gap_end := i })

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::move_right]:
    Source: 'src/gap_buffer.rs', lines 95:4-103:5 -/
def gap_buffer.GapBuffer.move_right
  (self : gap_buffer.GapBuffer) : Result (Bool × gap_buffer.GapBuffer) := do
  let i := alloc.vec.Vec.len self.buffer
  if self.gap_end = i
  then ok (false, self)
  else
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8)
        self.buffer self.gap_end
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.U8)
        self.buffer self.gap_start
    let i2 ← self.gap_start + 1#usize
    let i3 ← self.gap_end + 1#usize
    let v := index_mut_back i1
    ok (true, { buffer := v, gap_start := i2, gap_end := i3 })

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::cursor_pos]:
    Source: 'src/gap_buffer.rs', lines 106:4-108:5 -/
def gap_buffer.GapBuffer.cursor_pos
  (self : gap_buffer.GapBuffer) : Result Std.Usize := do
  ok self.gap_start

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::content_len]:
    Source: 'src/gap_buffer.rs', lines 111:4-113:5 -/
def gap_buffer.GapBuffer.content_len
  (self : gap_buffer.GapBuffer) : Result Std.Usize := do
  let i := alloc.vec.Vec.len self.buffer
  let i1 ← self.gap_end - self.gap_start
  i - i1

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::to_vec]: loop body 0:
    Source: 'src/gap_buffer.rs', lines 124:8-127:9 -/
@[rust_loop_body]
def gap_buffer.GapBuffer.to_vec_loop0.body
  (self : gap_buffer.GapBuffer) (result : alloc.vec.Vec Std.U8) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) ((alloc.vec.Vec
    Std.U8) × Std.Usize × (alloc.vec.Vec Std.U8)))
  := do
  if i < self.gap_start
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8)
        self.buffer i
    let result1 ← alloc.vec.Vec.push result i1
    let i2 ← i + 1#usize
    ok (cont (result1, i2))
  else ok (done (self.buffer, self.gap_end, result))

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::to_vec]: loop 0:
    Source: 'src/gap_buffer.rs', lines 124:8-127:9 -/
@[rust_loop]
def gap_buffer.GapBuffer.to_vec_loop0
  (self : gap_buffer.GapBuffer) (result : alloc.vec.Vec Std.U8) (i : Std.Usize)
  :
  Result ((alloc.vec.Vec Std.U8) × Std.Usize × (alloc.vec.Vec Std.U8))
  := do
  loop
    (fun (result1, i1) => gap_buffer.GapBuffer.to_vec_loop0.body self result1
      i1)
    (result, i)

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::to_vec]: loop body 1:
    Source: 'src/gap_buffer.rs', lines 131:8-134:9 -/
@[rust_loop_body]
def gap_buffer.GapBuffer.to_vec_loop1.body
  (v : alloc.vec.Vec Std.U8) (result : alloc.vec.Vec Std.U8) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i := alloc.vec.Vec.len v
  if j < i
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8) v j
    let result1 ← alloc.vec.Vec.push result i1
    let j1 ← j + 1#usize
    ok (cont (result1, j1))
  else ok (done result)

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::to_vec]: loop 1:
    Source: 'src/gap_buffer.rs', lines 131:8-134:9 -/
@[rust_loop]
def gap_buffer.GapBuffer.to_vec_loop1
  (v : alloc.vec.Vec Std.U8) (result : alloc.vec.Vec Std.U8) (j : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (result1, j1) => gap_buffer.GapBuffer.to_vec_loop1.body v result1 j1)
    (result, j)

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::to_vec]:
    Source: 'src/gap_buffer.rs', lines 119:4-137:5 -/
def gap_buffer.GapBuffer.to_vec
  (self : gap_buffer.GapBuffer) : Result (alloc.vec.Vec Std.U8) := do
  let (v, j, result) ←
    gap_buffer.GapBuffer.to_vec_loop0 self (alloc.vec.Vec.new Std.U8) 0#usize
  gap_buffer.GapBuffer.to_vec_loop1 v result j

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::gap_start]:
    Source: 'src/gap_buffer.rs', lines 140:4-142:5 -/
def gap_buffer.GapBuffer.impl.gap_start
  (self : gap_buffer.GapBuffer) : Result Std.Usize := do
  ok self.gap_start

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::gap_end]:
    Source: 'src/gap_buffer.rs', lines 145:4-147:5 -/
def gap_buffer.GapBuffer.impl.gap_end
  (self : gap_buffer.GapBuffer) : Result Std.Usize := do
  ok self.gap_end

/-- [buffer_management::gap_buffer::{buffer_management::gap_buffer::GapBuffer}::buffer_len]:
    Source: 'src/gap_buffer.rs', lines 150:4-152:5 -/
def gap_buffer.GapBuffer.buffer_len
  (self : gap_buffer.GapBuffer) : Result Std.Usize := do
  ok (alloc.vec.Vec.len self.buffer)

/-- [buffer_management::input_buffer::InputBuffer]
    Source: 'src/input_buffer.rs', lines 9:0-11:1 -/
structure input_buffer.InputBuffer where
  gap : gap_buffer.GapBuffer

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::new]:
    Source: 'src/input_buffer.rs', lines 15:4-19:5 -/
def input_buffer.InputBuffer.new
  (capacity : Std.Usize) : Result input_buffer.InputBuffer := do
  let gb ← gap_buffer.GapBuffer.new capacity
  ok { gap := gb }

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::insert_char]:
    Source: 'src/input_buffer.rs', lines 22:4-24:5 -/
def input_buffer.InputBuffer.insert_char
  (self : input_buffer.InputBuffer) (ch : Std.U8) :
  Result input_buffer.InputBuffer
  := do
  let gb ← gap_buffer.GapBuffer.insert self.gap ch
  ok { gap := gb }

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::backspace]:
    Source: 'src/input_buffer.rs', lines 28:4-30:5 -/
def input_buffer.InputBuffer.backspace
  (self : input_buffer.InputBuffer) :
  Result (Bool × input_buffer.InputBuffer)
  := do
  let (b, gb) ← gap_buffer.GapBuffer.delete_before self.gap
  ok (b, { gap := gb })

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::delete_word]: loop body 0:
    Source: 'src/input_buffer.rs', lines 41:8-54:9 -/
@[rust_loop_body]
def input_buffer.InputBuffer.delete_word_loop0.body
  (self : input_buffer.InputBuffer) (deleted_any : Bool) :
  Result (ControlFlow (input_buffer.InputBuffer × Bool) (gap_buffer.GapBuffer
    × Bool))
  := do
  let i ← gap_buffer.GapBuffer.cursor_pos self.gap
  if i > 0#usize
  then
    let content ← gap_buffer.GapBuffer.to_vec self.gap
    if i = 0#usize
    then ok (done (self.gap, deleted_any))
    else
      let i1 ← i - 1#usize
      let i2 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8)
          content i1
      if i2 != 32#u8
      then ok (done (self.gap, deleted_any))
      else
        let (_, gb) ← gap_buffer.GapBuffer.delete_before self.gap
        ok (cont ({ gap := gb }, true))
  else ok (done (self.gap, deleted_any))

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::delete_word]: loop 0:
    Source: 'src/input_buffer.rs', lines 41:8-54:9 -/
@[rust_loop]
def input_buffer.InputBuffer.delete_word_loop0
  (self : input_buffer.InputBuffer) (deleted_any : Bool) :
  Result (gap_buffer.GapBuffer × Bool)
  := do
  loop
    (fun (self1, deleted_any1) =>
      input_buffer.InputBuffer.delete_word_loop0.body self1 deleted_any1)
    (self, deleted_any)

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::delete_word]: loop body 1:
    Source: 'src/input_buffer.rs', lines 57:8-68:9 -/
@[rust_loop_body]
def input_buffer.InputBuffer.delete_word_loop1.body
  (gb : gap_buffer.GapBuffer) (deleted_any : Bool) :
  Result (ControlFlow (gap_buffer.GapBuffer × Bool) (gap_buffer.GapBuffer ×
    Bool))
  := do
  let i ← gap_buffer.GapBuffer.cursor_pos gb
  if i > 0#usize
  then
    let content ← gap_buffer.GapBuffer.to_vec gb
    if i = 0#usize
    then ok (done (gb, deleted_any))
    else
      let i1 ← i - 1#usize
      let i2 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8)
          content i1
      if i2 = 32#u8
      then ok (done (gb, deleted_any))
      else
        let (_, gb1) ← gap_buffer.GapBuffer.delete_before gb
        ok (cont (gb1, true))
  else ok (done (gb, deleted_any))

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::delete_word]: loop 1:
    Source: 'src/input_buffer.rs', lines 57:8-68:9 -/
@[rust_loop]
def input_buffer.InputBuffer.delete_word_loop1
  (gb : gap_buffer.GapBuffer) (deleted_any : Bool) :
  Result (gap_buffer.GapBuffer × Bool)
  := do
  loop
    (fun (gb1, deleted_any1) => input_buffer.InputBuffer.delete_word_loop1.body
      gb1 deleted_any1)
    (gb, deleted_any)

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::delete_word]:
    Source: 'src/input_buffer.rs', lines 37:4-71:5 -/
def input_buffer.InputBuffer.delete_word
  (self : input_buffer.InputBuffer) :
  Result (Bool × input_buffer.InputBuffer)
  := do
  let (gb, deleted_any) ←
    input_buffer.InputBuffer.delete_word_loop0 self false
  let (gb1, deleted_any1) ←
    input_buffer.InputBuffer.delete_word_loop1 gb deleted_any
  ok (deleted_any1, { gap := gb1 })

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::move_cursor_left]:
    Source: 'src/input_buffer.rs', lines 75:4-77:5 -/
def input_buffer.InputBuffer.move_cursor_left
  (self : input_buffer.InputBuffer) :
  Result (Bool × input_buffer.InputBuffer)
  := do
  let (b, gb) ← gap_buffer.GapBuffer.move_left self.gap
  ok (b, { gap := gb })

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::move_cursor_right]:
    Source: 'src/input_buffer.rs', lines 81:4-83:5 -/
def input_buffer.InputBuffer.move_cursor_right
  (self : input_buffer.InputBuffer) :
  Result (Bool × input_buffer.InputBuffer)
  := do
  let (b, gb) ← gap_buffer.GapBuffer.move_right self.gap
  ok (b, { gap := gb })

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::move_to_start]: loop body 0:
    Source: 'src/input_buffer.rs', lines 87:8-89:9 -/
@[rust_loop_body]
def input_buffer.InputBuffer.move_to_start_loop.body
  (self : input_buffer.InputBuffer) :
  Result (ControlFlow input_buffer.InputBuffer gap_buffer.GapBuffer)
  := do
  let i ← gap_buffer.GapBuffer.cursor_pos self.gap
  if i > 0#usize
  then
    let (_, gb) ← gap_buffer.GapBuffer.move_left self.gap
    ok (cont { gap := gb })
  else ok (done self.gap)

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::move_to_start]: loop 0:
    Source: 'src/input_buffer.rs', lines 87:8-89:9 -/
@[rust_loop]
def input_buffer.InputBuffer.move_to_start_loop
  (self : input_buffer.InputBuffer) : Result gap_buffer.GapBuffer := do
  loop
    (fun self1 => input_buffer.InputBuffer.move_to_start_loop.body self1)
    self

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::move_to_start]:
    Source: 'src/input_buffer.rs', lines 86:4-90:5 -/
def input_buffer.InputBuffer.move_to_start
  (self : input_buffer.InputBuffer) : Result input_buffer.InputBuffer := do
  let gb ← input_buffer.InputBuffer.move_to_start_loop self
  ok { gap := gb }

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::move_to_end]: loop body 0:
    Source: 'src/input_buffer.rs', lines 94:8-96:9 -/
@[rust_loop_body]
def input_buffer.InputBuffer.move_to_end_loop.body
  (self : input_buffer.InputBuffer) :
  Result (ControlFlow input_buffer.InputBuffer gap_buffer.GapBuffer)
  := do
  let i ← gap_buffer.GapBuffer.cursor_pos self.gap
  let i1 ← gap_buffer.GapBuffer.content_len self.gap
  if i < i1
  then
    let (_, gb) ← gap_buffer.GapBuffer.move_right self.gap
    ok (cont { gap := gb })
  else ok (done self.gap)

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::move_to_end]: loop 0:
    Source: 'src/input_buffer.rs', lines 94:8-96:9 -/
@[rust_loop]
def input_buffer.InputBuffer.move_to_end_loop
  (self : input_buffer.InputBuffer) : Result gap_buffer.GapBuffer := do
  loop
    (fun self1 => input_buffer.InputBuffer.move_to_end_loop.body self1)
    self

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::move_to_end]:
    Source: 'src/input_buffer.rs', lines 93:4-97:5 -/
def input_buffer.InputBuffer.move_to_end
  (self : input_buffer.InputBuffer) : Result input_buffer.InputBuffer := do
  let gb ← input_buffer.InputBuffer.move_to_end_loop self
  ok { gap := gb }

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::get_content]:
    Source: 'src/input_buffer.rs', lines 100:4-102:5 -/
def input_buffer.InputBuffer.get_content
  (self : input_buffer.InputBuffer) : Result (alloc.vec.Vec Std.U8) := do
  gap_buffer.GapBuffer.to_vec self.gap

/-- [buffer_management::input_buffer::{buffer_management::input_buffer::InputBuffer}::cursor_position]:
    Source: 'src/input_buffer.rs', lines 105:4-107:5 -/
def input_buffer.InputBuffer.cursor_position
  (self : input_buffer.InputBuffer) : Result Std.Usize := do
  gap_buffer.GapBuffer.cursor_pos self.gap

/-- [buffer_management::ring_buffer::RingBuffer]
    Source: 'src/ring_buffer.rs', lines 11:0-17:1 -/
structure ring_buffer.RingBuffer {T : Type} (corecloneCloneInst :
  core.clone.Clone T) (coredefaultDefaultInst : core.default.Default T) where
  data : alloc.vec.Vec T
  capacity : Std.Usize
  head : Std.Usize
  tail : Std.Usize
  len : Std.Usize

/-- [buffer_management::ring_buffer::{buffer_management::ring_buffer::RingBuffer<T>[TraitClause@0, TraitClause@1]}::new]: loop body 0:
    Source: 'src/ring_buffer.rs', lines 28:8-31:9 -/
@[rust_loop_body]
def ring_buffer.RingBuffer.new_loop.body
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (capacity : Std.Usize) (data : alloc.vec.Vec T) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec T) × Std.Usize) (alloc.vec.Vec T))
  := do
  if i < capacity
  then
    let t ← coredefaultDefaultInst.default
    let data1 ← alloc.vec.Vec.push data t
    let i1 ← i + 1#usize
    ok (cont (data1, i1))
  else ok (done data)

/-- [buffer_management::ring_buffer::{buffer_management::ring_buffer::RingBuffer<T>[TraitClause@0, TraitClause@1]}::new]: loop 0:
    Source: 'src/ring_buffer.rs', lines 28:8-31:9 -/
@[rust_loop]
def ring_buffer.RingBuffer.new_loop
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (capacity : Std.Usize) (data : alloc.vec.Vec T) (i : Std.Usize) :
  Result (alloc.vec.Vec T)
  := do
  loop
    (fun (data1, i1) => ring_buffer.RingBuffer.new_loop.body
      coredefaultDefaultInst capacity data1 i1)
    (data, i)

/-- [buffer_management::ring_buffer::{buffer_management::ring_buffer::RingBuffer<T>[TraitClause@0, TraitClause@1]}::new]:
    Source: 'src/ring_buffer.rs', lines 24:4-39:5 -/
def ring_buffer.RingBuffer.new
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (coredefaultDefaultInst
  : core.default.Default T) (capacity : Std.Usize) :
  Result (ring_buffer.RingBuffer corecloneCloneInst coredefaultDefaultInst)
  := do
  let data ←
    ring_buffer.RingBuffer.new_loop coredefaultDefaultInst capacity
      (alloc.vec.Vec.new T) 0#usize
  ok { data, capacity, head := 0#usize, tail := 0#usize, len := 0#usize }

/-- [buffer_management::ring_buffer::{buffer_management::ring_buffer::RingBuffer<T>[TraitClause@0, TraitClause@1]}::push]:
    Source: 'src/ring_buffer.rs', lines 42:4-50:5 -/
def ring_buffer.RingBuffer.push
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (coredefaultDefaultInst
  : core.default.Default T)
  (self : ring_buffer.RingBuffer corecloneCloneInst coredefaultDefaultInst)
  (item : T) :
  Result (Bool × (ring_buffer.RingBuffer corecloneCloneInst
    coredefaultDefaultInst))
  := do
  if self.len = self.capacity
  then ok (false, self)
  else
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice T)
        self.data self.tail
    let i ← self.tail + 1#usize
    let i1 ← i % self.capacity
    let i2 ← self.len + 1#usize
    let v := index_mut_back item
    ok (true, { self with data := v, tail := i1, len := i2 })

/-- [buffer_management::ring_buffer::{buffer_management::ring_buffer::RingBuffer<T>[TraitClause@0, TraitClause@1]}::pop]:
    Source: 'src/ring_buffer.rs', lines 57:4-66:5 -/
def ring_buffer.RingBuffer.pop
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (coredefaultDefaultInst
  : core.default.Default T)
  (self : ring_buffer.RingBuffer corecloneCloneInst coredefaultDefaultInst) :
  Result ((Bool × T) × (ring_buffer.RingBuffer corecloneCloneInst
    coredefaultDefaultInst))
  := do
  if self.len = 0#usize
  then let t ← coredefaultDefaultInst.default
       ok ((false, t), self)
  else
    let t ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) self.data
        self.head
    let item ← corecloneCloneInst.clone t
    let t1 ← coredefaultDefaultInst.default
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice T)
        self.data self.head
    let i ← self.head + 1#usize
    let i1 ← i % self.capacity
    let i2 ← self.len - 1#usize
    let v := index_mut_back t1
    ok ((true, item), { self with data := v, head := i1, len := i2 })

/-- [buffer_management::ring_buffer::{buffer_management::ring_buffer::RingBuffer<T>[TraitClause@0, TraitClause@1]}::peek]:
    Source: 'src/ring_buffer.rs', lines 72:4-77:5 -/
def ring_buffer.RingBuffer.peek
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (coredefaultDefaultInst
  : core.default.Default T)
  (self : ring_buffer.RingBuffer corecloneCloneInst coredefaultDefaultInst) :
  Result (Bool × T)
  := do
  if self.len = 0#usize
  then let t ← coredefaultDefaultInst.default
       ok (false, t)
  else
    let t ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) self.data
        self.head
    let t1 ← corecloneCloneInst.clone t
    ok (true, t1)

/-- [buffer_management::ring_buffer::{buffer_management::ring_buffer::RingBuffer<T>[TraitClause@0, TraitClause@1]}::is_full]:
    Source: 'src/ring_buffer.rs', lines 80:4-82:5 -/
def ring_buffer.RingBuffer.is_full
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (coredefaultDefaultInst
  : core.default.Default T)
  (self : ring_buffer.RingBuffer corecloneCloneInst coredefaultDefaultInst) :
  Result Bool
  := do
  ok (self.len = self.capacity)

/-- [buffer_management::ring_buffer::{buffer_management::ring_buffer::RingBuffer<T>[TraitClause@0, TraitClause@1]}::is_empty]:
    Source: 'src/ring_buffer.rs', lines 85:4-87:5 -/
def ring_buffer.RingBuffer.is_empty
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (coredefaultDefaultInst
  : core.default.Default T)
  (self : ring_buffer.RingBuffer corecloneCloneInst coredefaultDefaultInst) :
  Result Bool
  := do
  ok (self.len = 0#usize)

/-- [buffer_management::ring_buffer::{buffer_management::ring_buffer::RingBuffer<T>[TraitClause@0, TraitClause@1]}::len]:
    Source: 'src/ring_buffer.rs', lines 90:4-92:5 -/
def ring_buffer.RingBuffer.impl.len
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (coredefaultDefaultInst
  : core.default.Default T)
  (self : ring_buffer.RingBuffer corecloneCloneInst coredefaultDefaultInst) :
  Result Std.Usize
  := do
  ok self.len

/-- [buffer_management::ring_buffer::{buffer_management::ring_buffer::RingBuffer<T>[TraitClause@0, TraitClause@1]}::capacity]:
    Source: 'src/ring_buffer.rs', lines 95:4-97:5 -/
def ring_buffer.RingBuffer.impl.capacity
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (coredefaultDefaultInst
  : core.default.Default T)
  (self : ring_buffer.RingBuffer corecloneCloneInst coredefaultDefaultInst) :
  Result Std.Usize
  := do
  ok self.capacity

end buffer_management
