-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [infix_calc]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace infix_calc

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field3_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2637:4-2643:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field3_finish] -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field3_finish"]
axiom core.fmt.Formatter.debug_tuple_field3_finish
  :
  core.fmt.Formatter → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Dyn
    (fun _dyn => core.fmt.Debug _dyn) → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::ops::range::RangeInclusive]
    Source: '/rustc/library/core/src/ops/range.rs', lines 357:0-357:30
    Name pattern: [core::ops::range::RangeInclusive] -/
@[rust_type "core::ops::range::RangeInclusive"]
axiom core.ops.range.RangeInclusive (Idx : Type) : Type

/-- [core::ops::range::{core::ops::range::RangeInclusive<Idx>}::new]:
    Source: '/rustc/library/core/src/ops/range.rs', lines 390:4-390:50
    Name pattern: [core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::new] -/
@[rust_fun "core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::new"]
axiom core.ops.range.RangeInclusive.new
  {Idx : Type} : Idx → Idx → Result (core.ops.range.RangeInclusive Idx)

/-- [core::ops::range::{core::ops::range::RangeInclusive<Idx>}::contains]:
    Source: '/rustc/library/core/src/ops/range.rs', lines 522:4-525:44
    Name pattern: [core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::contains] -/
@[rust_fun
  "core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::contains"]
axiom core.ops.range.RangeInclusive.contains
  {Idx : Type} {U : Type} (cmpPartialOrdInst : core.cmp.PartialOrd Idx Idx)
  (cmpPartialOrdInst1 : core.cmp.PartialOrd Idx U) (cmpPartialOrdInst2 :
  core.cmp.PartialOrd U Idx) :
  core.ops.range.RangeInclusive Idx → U → Result Bool

/-- [core::option::{core::option::Option<T>}::ok_or]:
    Source: '/rustc/library/core/src/option.rs', lines 1337:4-1337:73
    Name pattern: [core::option::{core::option::Option<@T>}::ok_or] -/
@[rust_fun "core::option::{core::option::Option<@T>}::ok_or"]
axiom core.option.Option.ok_or
  {T : Type} {E : Type} : Option T → E → Result (core.result.Result T E)

/-- [core::result::{core::ops::try_trait::Try<T, core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2172:4-2172:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch] -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch"]
axiom core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
  {T : Type} {E : Type} :
  core.result.Result T E → Result (core.ops.control_flow.ControlFlow
    (core.result.Result core.convert.Infallible E) T)

/-- [core::result::{core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2187:4-2187:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual] -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
axiom
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
  (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
  core.result.Result core.convert.Infallible E → Result (core.result.Result T
    F)

/-- [core::slice::{[T]}::last]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 281:4-281:42
    Name pattern: [core::slice::{[@T]}::last] -/
@[rust_fun "core::slice::{[@T]}::last"]
axiom core.slice.Slice.last {T : Type} : Slice T → Result (Option T)

/-- [alloc::boxed::{core::fmt::Debug for alloc::boxed::Box<T>}::fmt]:
    Source: '/rustc/library/alloc/src/boxed.rs', lines 2164:4-2164:60
    Name pattern: [alloc::boxed::{core::fmt::Debug<Box<@T>>}::fmt] -/
@[rust_fun "alloc::boxed::{core::fmt::Debug<Box<@T>>}::fmt"]
axiom Box.Insts.CoreFmtDebug.fmt
  {T : Type} (A : Type) (corefmtDebugInst : core.fmt.Debug T) :
  T → core.fmt.Formatter → Result ((core.result.Result Unit core.fmt.Error)
    × core.fmt.Formatter)

/-- Trait implementation: [alloc::boxed::{core::fmt::Debug for alloc::boxed::Box<T>}]
    Source: '/rustc/library/alloc/src/boxed.rs', lines 2163:0-2163:67
    Name pattern: [core::fmt::Debug<Box<@T>>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<Box<@T>>"]
def Box.Insts.CoreFmtDebug {T : Type} (A : Type) (corefmtDebugInst :
  core.fmt.Debug T) : core.fmt.Debug T := {
  fmt := Box.Insts.CoreFmtDebug.fmt A corefmtDebugInst
}

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2956:4-2956:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty] -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

/-- [infix_calc::Op]
    Source: 'src/lib.rs', lines 13:0-18:1 -/
@[discriminant isize]
inductive Op where
| Add : Op
| Sub : Op
| Mul : Op
| Div : Op

/-- [infix_calc::{core::clone::Clone for infix_calc::Op}::clone]:
    Source: 'src/lib.rs', lines 12:9-12:14 -/
def Op.Insts.CoreCloneClone.clone (self : Op) : Result Op := do
  match self with
  | Op.Add => ok Op.Add
  | Op.Sub => ok Op.Sub
  | Op.Mul => ok Op.Mul
  | Op.Div => ok Op.Div

/-- Trait implementation: [infix_calc::{core::clone::Clone for infix_calc::Op}]
    Source: 'src/lib.rs', lines 12:9-12:14 -/
@[reducible]
def Op.Insts.CoreCloneClone : core.clone.Clone Op := {
  clone := Op.Insts.CoreCloneClone.clone
}

/-- [infix_calc::{core::fmt::Debug for infix_calc::Op}::fmt]:
    Source: 'src/lib.rs', lines 12:16-12:21 -/
def Op.Insts.CoreFmtDebug.fmt
  (self : Op) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | Op.Add => core.fmt.Formatter.write_str f (toStr "Add")
  | Op.Sub => core.fmt.Formatter.write_str f (toStr "Sub")
  | Op.Mul => core.fmt.Formatter.write_str f (toStr "Mul")
  | Op.Div => core.fmt.Formatter.write_str f (toStr "Div")

/-- Trait implementation: [infix_calc::{core::fmt::Debug for infix_calc::Op}]
    Source: 'src/lib.rs', lines 12:16-12:21 -/
@[reducible]
def Op.Insts.CoreFmtDebug : core.fmt.Debug Op := {
  fmt := Op.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [infix_calc::{core::marker::StructuralPartialEq for infix_calc::Op}]
    Source: 'src/lib.rs', lines 12:23-12:32 -/
@[reducible]
def Op.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq Op
  := {
}

/-- [infix_calc::{core::cmp::PartialEq<infix_calc::Op> for infix_calc::Op}::eq]:
    Source: 'src/lib.rs', lines 12:23-12:32 -/
def Op.Insts.CoreCmpPartialEqOp.eq (self : Op) (other : Op) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [infix_calc::{core::cmp::PartialEq<infix_calc::Op> for infix_calc::Op}]
    Source: 'src/lib.rs', lines 12:23-12:32 -/
@[reducible]
def Op.Insts.CoreCmpPartialEqOp : core.cmp.PartialEq Op Op := {
  eq := Op.Insts.CoreCmpPartialEqOp.eq
}

/-- [infix_calc::Token]
    Source: 'src/lib.rs', lines 22:0-27:1 -/
@[discriminant isize]
inductive Token where
| Num : Std.I64 → Token
| Operator : Op → Token
| LParen : Token
| RParen : Token

/-- [infix_calc::{core::clone::Clone for infix_calc::Token}::clone]:
    Source: 'src/lib.rs', lines 21:9-21:14 -/
def Token.Insts.CoreCloneClone.clone (self : Token) : Result Token := do
  match self with
  | Token.Num __self_0 =>
    let i ← lift (core.clone.impls.CloneI64.clone __self_0)
    ok (Token.Num i)
  | Token.Operator __self_0 =>
    let o ← Op.Insts.CoreCloneClone.clone __self_0
    ok (Token.Operator o)
  | Token.LParen => ok Token.LParen
  | Token.RParen => ok Token.RParen

/-- Trait implementation: [infix_calc::{core::clone::Clone for infix_calc::Token}]
    Source: 'src/lib.rs', lines 21:9-21:14 -/
@[reducible]
def Token.Insts.CoreCloneClone : core.clone.Clone Token := {
  clone := Token.Insts.CoreCloneClone.clone
}

/-- [infix_calc::{core::fmt::Debug for infix_calc::Token}::fmt]:
    Source: 'src/lib.rs', lines 21:16-21:21 -/
def Token.Insts.CoreFmtDebug.fmt
  (self : Token) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | Token.Num __self_0 =>
    let __self_01 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugI64) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Num") __self_01
  | Token.Operator __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared Op.Insts.CoreFmtDebug) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Operator") __self_01
  | Token.LParen => core.fmt.Formatter.write_str f (toStr "LParen")
  | Token.RParen => core.fmt.Formatter.write_str f (toStr "RParen")

/-- Trait implementation: [infix_calc::{core::fmt::Debug for infix_calc::Token}]
    Source: 'src/lib.rs', lines 21:16-21:21 -/
@[reducible]
def Token.Insts.CoreFmtDebug : core.fmt.Debug Token := {
  fmt := Token.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [infix_calc::{core::marker::StructuralPartialEq for infix_calc::Token}]
    Source: 'src/lib.rs', lines 21:23-21:32 -/
@[reducible]
def Token.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Token := {
}

/-- [infix_calc::{core::cmp::PartialEq<infix_calc::Token> for infix_calc::Token}::eq]:
    Source: 'src/lib.rs', lines 21:23-21:32 -/
def Token.Insts.CoreCmpPartialEqToken.eq
  (self : Token) (other : Token) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | Token.Num __self_0 =>
      match other with
      | Token.Num __arg1_0 =>
        lift (core.cmp.impls.PartialEqI64.eq __self_0 __arg1_0)
      | Token.Operator _ => ok true
      | Token.LParen => ok true
      | Token.RParen => ok true
    | Token.Operator __self_0 =>
      match other with
      | Token.Num _ => ok true
      | Token.Operator __arg1_0 =>
        Op.Insts.CoreCmpPartialEqOp.eq __self_0 __arg1_0
      | Token.LParen => ok true
      | Token.RParen => ok true
    | Token.LParen => ok true
    | Token.RParen => ok true
  else ok false

/-- Trait implementation: [infix_calc::{core::cmp::PartialEq<infix_calc::Token> for infix_calc::Token}]
    Source: 'src/lib.rs', lines 21:23-21:32 -/
@[reducible]
def Token.Insts.CoreCmpPartialEqToken : core.cmp.PartialEq Token Token := {
  eq := Token.Insts.CoreCmpPartialEqToken.eq
}

/-- [infix_calc::Expr]
    Source: 'src/lib.rs', lines 32:0-35:1 -/
@[discriminant isize]
inductive Expr where
| Num : Std.I64 → Expr
| BinOp : Op → Expr → Expr → Expr

/-- [infix_calc::{core::clone::Clone for infix_calc::Expr}::clone]:
    Source: 'src/lib.rs', lines 31:9-31:14 -/
def Expr.Insts.CoreCloneClone.clone (self : Expr) : Result Expr := do
  match self with
  | Expr.Num __self_0 =>
    let i ← lift (core.clone.impls.CloneI64.clone __self_0)
    ok (Expr.Num i)
  | Expr.BinOp __self_0 __self_1 __self_2 =>
    let o ← Op.Insts.CoreCloneClone.clone __self_0
    let e ← Expr.Insts.CoreCloneClone.clone __self_1
    let e1 ← Expr.Insts.CoreCloneClone.clone __self_2
    ok (Expr.BinOp o e e1)
partial_fixpoint

/-- Trait implementation: [infix_calc::{core::clone::Clone for infix_calc::Expr}]
    Source: 'src/lib.rs', lines 31:9-31:14 -/
@[reducible]
def Expr.Insts.CoreCloneClone : core.clone.Clone Expr := {
  clone := Expr.Insts.CoreCloneClone.clone
}

/-- [infix_calc::{core::fmt::Debug for infix_calc::Expr}::fmt]:
    Source: 'src/lib.rs', lines 31:16-31:21 -/
def Expr.Insts.CoreFmtDebug.fmt
  (self : Expr) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | Expr.Num __self_0 =>
    let __self_01 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugI64) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Num") __self_01
  | Expr.BinOp __self_0 __self_1 __self_2 =>
    let __self_01 := Dyn.mk _ Op.Insts.CoreFmtDebug __self_0
    let __self_11 :=
      Dyn.mk _ (Box.Insts.CoreFmtDebug Global Expr.Insts.CoreFmtDebug) __self_1
    let __self_21 :=
      Dyn.mk _ (core.fmt.DebugShared (Box.Insts.CoreFmtDebug Global
        Expr.Insts.CoreFmtDebug)) __self_2
    core.fmt.Formatter.debug_tuple_field3_finish f (toStr "BinOp") __self_01
      __self_11 __self_21

/-- Trait implementation: [infix_calc::{core::fmt::Debug for infix_calc::Expr}]
    Source: 'src/lib.rs', lines 31:16-31:21 -/
@[reducible]
def Expr.Insts.CoreFmtDebug : core.fmt.Debug Expr := {
  fmt := Expr.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [infix_calc::{core::marker::StructuralPartialEq for infix_calc::Expr}]
    Source: 'src/lib.rs', lines 31:23-31:32 -/
@[reducible]
def Expr.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Expr := {
}

/-- [infix_calc::{core::cmp::PartialEq<infix_calc::Expr> for infix_calc::Expr}::eq]:
    Source: 'src/lib.rs', lines 31:23-31:32 -/
def Expr.Insts.CoreCmpPartialEqExpr.eq
  (self : Expr) (other : Expr) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | Expr.Num __self_0 =>
      match other with
      | Expr.Num __arg1_0 =>
        lift (core.cmp.impls.PartialEqI64.eq __self_0 __arg1_0)
      | Expr.BinOp _ _ _ => fail panic
    | Expr.BinOp __self_0 __self_1 __self_2 =>
      match other with
      | Expr.Num _ => fail panic
      | Expr.BinOp __arg1_0 __arg1_1 __arg1_2 =>
        let b ← Op.Insts.CoreCmpPartialEqOp.eq __self_0 __arg1_0
        if b
        then
          let b1 ← Expr.Insts.CoreCmpPartialEqExpr.eq __self_1 __arg1_1
          if b1
          then Expr.Insts.CoreCmpPartialEqExpr.eq __self_2 __arg1_2
          else ok false
        else ok false
  else ok false
partial_fixpoint

/-- Trait implementation: [infix_calc::{core::cmp::PartialEq<infix_calc::Expr> for infix_calc::Expr}]
    Source: 'src/lib.rs', lines 31:23-31:32 -/
@[reducible]
def Expr.Insts.CoreCmpPartialEqExpr : core.cmp.PartialEq Expr Expr := {
  eq := Expr.Insts.CoreCmpPartialEqExpr.eq
}

/-- [infix_calc::ParseError]
    Source: 'src/lib.rs', lines 39:0-43:1 -/
@[discriminant isize]
inductive ParseError where
| UnexpectedToken : ParseError
| UnexpectedEnd : ParseError
| TrailingTokens : ParseError

/-- [infix_calc::{core::clone::Clone for infix_calc::ParseError}::clone]:
    Source: 'src/lib.rs', lines 38:9-38:14 -/
def ParseError.Insts.CoreCloneClone.clone
  (self : ParseError) : Result ParseError := do
  match self with
  | ParseError.UnexpectedToken => ok ParseError.UnexpectedToken
  | ParseError.UnexpectedEnd => ok ParseError.UnexpectedEnd
  | ParseError.TrailingTokens => ok ParseError.TrailingTokens

/-- Trait implementation: [infix_calc::{core::clone::Clone for infix_calc::ParseError}]
    Source: 'src/lib.rs', lines 38:9-38:14 -/
@[reducible]
def ParseError.Insts.CoreCloneClone : core.clone.Clone ParseError := {
  clone := ParseError.Insts.CoreCloneClone.clone
}

/-- [infix_calc::{core::fmt::Debug for infix_calc::ParseError}::fmt]:
    Source: 'src/lib.rs', lines 38:16-38:21 -/
def ParseError.Insts.CoreFmtDebug.fmt
  (self : ParseError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | ParseError.UnexpectedToken =>
    core.fmt.Formatter.write_str f (toStr "UnexpectedToken")
  | ParseError.UnexpectedEnd =>
    core.fmt.Formatter.write_str f (toStr "UnexpectedEnd")
  | ParseError.TrailingTokens =>
    core.fmt.Formatter.write_str f (toStr "TrailingTokens")

/-- Trait implementation: [infix_calc::{core::fmt::Debug for infix_calc::ParseError}]
    Source: 'src/lib.rs', lines 38:16-38:21 -/
@[reducible]
def ParseError.Insts.CoreFmtDebug : core.fmt.Debug ParseError := {
  fmt := ParseError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [infix_calc::{core::marker::StructuralPartialEq for infix_calc::ParseError}]
    Source: 'src/lib.rs', lines 38:23-38:32 -/
@[reducible]
def ParseError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ParseError := {
}

/-- [infix_calc::{core::cmp::PartialEq<infix_calc::ParseError> for infix_calc::ParseError}::eq]:
    Source: 'src/lib.rs', lines 38:23-38:32 -/
def ParseError.Insts.CoreCmpPartialEqParseError.eq
  (self : ParseError) (other : ParseError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [infix_calc::{core::cmp::PartialEq<infix_calc::ParseError> for infix_calc::ParseError}]
    Source: 'src/lib.rs', lines 38:23-38:32 -/
@[reducible]
def ParseError.Insts.CoreCmpPartialEqParseError : core.cmp.PartialEq ParseError
  ParseError := {
  eq := ParseError.Insts.CoreCmpPartialEqParseError.eq
}

/-- [infix_calc::EvalError]
    Source: 'src/lib.rs', lines 47:0-50:1 -/
@[discriminant isize]
inductive EvalError where
| DivisionByZero : EvalError
| Overflow : EvalError

/-- [infix_calc::{core::clone::Clone for infix_calc::EvalError}::clone]:
    Source: 'src/lib.rs', lines 46:9-46:14 -/
def EvalError.Insts.CoreCloneClone.clone
  (self : EvalError) : Result EvalError := do
  match self with
  | EvalError.DivisionByZero => ok EvalError.DivisionByZero
  | EvalError.Overflow => ok EvalError.Overflow

/-- Trait implementation: [infix_calc::{core::clone::Clone for infix_calc::EvalError}]
    Source: 'src/lib.rs', lines 46:9-46:14 -/
@[reducible]
def EvalError.Insts.CoreCloneClone : core.clone.Clone EvalError := {
  clone := EvalError.Insts.CoreCloneClone.clone
}

/-- [infix_calc::{core::fmt::Debug for infix_calc::EvalError}::fmt]:
    Source: 'src/lib.rs', lines 46:16-46:21 -/
def EvalError.Insts.CoreFmtDebug.fmt
  (self : EvalError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | EvalError.DivisionByZero =>
    core.fmt.Formatter.write_str f (toStr "DivisionByZero")
  | EvalError.Overflow => core.fmt.Formatter.write_str f (toStr "Overflow")

/-- Trait implementation: [infix_calc::{core::fmt::Debug for infix_calc::EvalError}]
    Source: 'src/lib.rs', lines 46:16-46:21 -/
@[reducible]
def EvalError.Insts.CoreFmtDebug : core.fmt.Debug EvalError := {
  fmt := EvalError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [infix_calc::{core::marker::StructuralPartialEq for infix_calc::EvalError}]
    Source: 'src/lib.rs', lines 46:23-46:32 -/
@[reducible]
def EvalError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq EvalError := {
}

/-- [infix_calc::{core::cmp::PartialEq<infix_calc::EvalError> for infix_calc::EvalError}::eq]:
    Source: 'src/lib.rs', lines 46:23-46:32 -/
def EvalError.Insts.CoreCmpPartialEqEvalError.eq
  (self : EvalError) (other : EvalError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [infix_calc::{core::cmp::PartialEq<infix_calc::EvalError> for infix_calc::EvalError}]
    Source: 'src/lib.rs', lines 46:23-46:32 -/
@[reducible]
def EvalError.Insts.CoreCmpPartialEqEvalError : core.cmp.PartialEq EvalError
  EvalError := {
  eq := EvalError.Insts.CoreCmpPartialEqEvalError.eq
}

/-- [infix_calc::lex]: loop body 1:
    Source: 'src/lib.rs', lines 1:0-91:17 -/
@[rust_loop_body]
def lex_loop0_loop0.body
  (input : Slice Std.U8) (i : Std.Usize) (value : Std.I64) :
  Result (ControlFlow (Std.Usize × Std.I64) (Std.Usize × Std.I64))
  := do
  let i1 := Slice.len input
  if i < i1
  then
    let i2 ← Slice.index_usize input i
    if i2 >= 48#u8
    then
      if i2 <= 57#u8
      then
        let i3 ← value * 10#i64
        let i4 ← i2 - 48#u8
        let i5 ← lift (UScalar.hcast .I64 i4)
        let value1 ← i3 + i5
        let i6 ← i + 1#usize
        ok (cont (i6, value1))
      else ok (done (i, value))
    else ok (done (i, value))
  else ok (done (i, value))

/-- [infix_calc::lex]: loop 1:
    Source: 'src/lib.rs', lines 1:0-91:17 -/
@[rust_loop]
def lex_loop0_loop0
  (input : Slice Std.U8) (i : Std.Usize) (value : Std.I64) :
  Result (Std.Usize × Std.I64)
  := do
  loop
    (fun (i1, value1) => lex_loop0_loop0.body input i1 value1)
    (i, value)

/-- [infix_calc::lex]: loop body 2:
    Source: 'src/lib.rs', lines 1:0-115:13 -/
@[rust_loop_body]
def lex_loop0_loop1.body
  (input : Slice Std.U8) (i : Std.Usize) (value : Std.I64) :
  Result (ControlFlow (Std.Usize × Std.I64) (Std.Usize × Std.I64))
  := do
  let i1 := Slice.len input
  if i < i1
  then
    let i2 ← Slice.index_usize input i
    if i2 >= 48#u8
    then
      if i2 <= 57#u8
      then
        let i3 ← value * 10#i64
        let i4 ← i2 - 48#u8
        let i5 ← lift (UScalar.hcast .I64 i4)
        let value1 ← i3 + i5
        let i6 ← i + 1#usize
        ok (cont (i6, value1))
      else ok (done (i, value))
    else ok (done (i, value))
  else ok (done (i, value))

/-- [infix_calc::lex]: loop 2:
    Source: 'src/lib.rs', lines 1:0-115:13 -/
@[rust_loop]
def lex_loop0_loop1
  (input : Slice Std.U8) (i : Std.Usize) (value : Std.I64) :
  Result (Std.Usize × Std.I64)
  := do
  loop
    (fun (i1, value1) => lex_loop0_loop1.body input i1 value1)
    (i, value)

/-- [infix_calc::lex]: loop body 0:
    Source: 'src/lib.rs', lines 0:0-123:1 -/
@[rust_loop_body]
def lex_loop0.body
  (input : Slice Std.U8) (tokens : alloc.vec.Vec Token) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Token) × Std.Usize) (core.result.Result
    (alloc.vec.Vec Token) ParseError))
  := do
  let i1 := Slice.len input
  if i < i1
  then
    let ch ← Slice.index_usize input i
    if ch = 32#u8
    then let i2 ← i + 1#usize
         ok (cont (tokens, i2))
    else
      if ch = 9#u8
      then let i2 ← i + 1#usize
           ok (cont (tokens, i2))
      else
        if ch = 10#u8
        then let i2 ← i + 1#usize
             ok (cont (tokens, i2))
        else
          if ch = 13#u8
          then let i2 ← i + 1#usize
               ok (cont (tokens, i2))
          else
            if ch = 43#u8
            then
              let tokens1 ← alloc.vec.Vec.push tokens (Token.Operator Op.Add)
              let i2 ← i + 1#usize
              ok (cont (tokens1, i2))
            else
              if ch = 45#u8
              then
                let i2 ← i + 1#usize
                let i3 := Slice.len input
                let is_unary ←
                  if i2 < i3
                  then
                    let i4 ← Slice.index_usize input i2
                    if i4 >= 48#u8
                    then
                      let i5 ← Slice.index_usize input i2
                      if i5 <= 57#u8
                      then
                        let b ← alloc.vec.Vec.is_empty Global tokens
                        if b
                        then ok true
                        else
                          let s := alloc.vec.Vec.deref tokens
                          let o ← core.slice.Slice.last s
                          match o with
                          | none => ok false
                          | some t =>
                            match t with
                            | Token.Num _ => ok false
                            | Token.Operator _ => ok true
                            | Token.LParen => ok true
                            | Token.RParen => ok false
                      else ok false
                    else ok false
                  else ok false
                if is_unary
                then
                  let (i4, value) ← lex_loop0_loop0 input i2 0#i64
                  let i5 ← -. value
                  let tokens1 ← alloc.vec.Vec.push tokens (Token.Num i5)
                  ok (cont (tokens1, i4))
                else
                  let tokens1 ←
                    alloc.vec.Vec.push tokens (Token.Operator Op.Sub)
                  ok (cont (tokens1, i2))
              else
                if ch = 42#u8
                then
                  let tokens1 ←
                    alloc.vec.Vec.push tokens (Token.Operator Op.Mul)
                  let i2 ← i + 1#usize
                  ok (cont (tokens1, i2))
                else
                  if ch = 47#u8
                  then
                    let tokens1 ←
                      alloc.vec.Vec.push tokens (Token.Operator Op.Div)
                    let i2 ← i + 1#usize
                    ok (cont (tokens1, i2))
                  else
                    if ch = 40#u8
                    then
                      let tokens1 ← alloc.vec.Vec.push tokens Token.LParen
                      let i2 ← i + 1#usize
                      ok (cont (tokens1, i2))
                    else
                      if ch = 41#u8
                      then
                        let tokens1 ← alloc.vec.Vec.push tokens Token.RParen
                        let i2 ← i + 1#usize
                        ok (cont (tokens1, i2))
                      else
                        let ri ←
                          core.ops.range.RangeInclusive.new 48#u8 57#u8
                        let b ←
                          core.ops.range.RangeInclusive.contains
                            core.cmp.PartialOrdU8 core.cmp.PartialOrdU8
                            core.cmp.PartialOrdU8 ri ch
                        if b
                        then
                          let (i2, value) ← lex_loop0_loop1 input i 0#i64
                          let tokens1 ←
                            alloc.vec.Vec.push tokens (Token.Num value)
                          ok (cont (tokens1, i2))
                        else
                          ok (done (core.result.Result.Err
                            ParseError.UnexpectedToken))
  else ok (done (core.result.Result.Ok tokens))

/-- [infix_calc::lex]: loop 0:
    Source: 'src/lib.rs', lines 0:0-123:1 -/
@[rust_loop]
def lex_loop0
  (input : Slice Std.U8) (tokens : alloc.vec.Vec Token) (i : Std.Usize) :
  Result (core.result.Result (alloc.vec.Vec Token) ParseError)
  := do
  loop
    (fun (tokens1, i1) => lex_loop0.body input tokens1 i1)
    (tokens, i)

/-- [infix_calc::lex]:
    Source: 'src/lib.rs', lines 59:0-123:1 -/
@[reducible]
def lex
  (input : Slice Std.U8) :
  Result (core.result.Result (alloc.vec.Vec Token) ParseError)
  := do
  lex_loop0 input (alloc.vec.Vec.new Token) 0#usize

mutual

/-- [infix_calc::parse_expr]: loop 0:
    Source: 'src/lib.rs', lines 1:0-151:1 -/
@[rust_loop]
def parse_expr_loop
  (tokens : Slice Token) (left : Expr) (pos : Std.Usize) :
  Result (core.result.Result (Expr × Std.Usize) ParseError)
  := do
  loop
    (fun (left1, pos1) => parse_expr_loop.body tokens left1 pos1)
    (left, pos)
partial_fixpoint

/-- [infix_calc::parse_expr]: loop body 0:
    Source: 'src/lib.rs', lines 1:0-151:1 -/
@[rust_loop_body]
def parse_expr_loop.body
  (tokens : Slice Token) (left : Expr) (pos : Std.Usize) :
  Result (ControlFlow (Expr × Std.Usize) (core.result.Result (Expr ×
    Std.Usize) ParseError))
  := do
  let i := Slice.len tokens
  if pos < i
  then
    let t ← Slice.index_usize tokens pos
    match t with
    | Token.Num _ => ok (done (core.result.Result.Ok (left, pos)))
    | Token.Operator o =>
      match o with
      | Op.Add =>
        let i1 ← pos + 1#usize
        let r ← parse_term tokens i1
        let cf ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let (right, next) := val
          ok (cont (Expr.BinOp Op.Add left right, next))
        | core.ops.control_flow.ControlFlow.Break residual =>
          let r1 ←
            core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
              (Expr × Std.Usize) (core.convert.FromSame ParseError) residual
          ok (done r1)
      | Op.Sub =>
        let i1 ← pos + 1#usize
        let r ← parse_term tokens i1
        let cf ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let (right, next) := val
          ok (cont (Expr.BinOp Op.Sub left right, next))
        | core.ops.control_flow.ControlFlow.Break residual =>
          let r1 ←
            core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
              (Expr × Std.Usize) (core.convert.FromSame ParseError) residual
          ok (done r1)
      | Op.Mul => ok (done (core.result.Result.Ok (left, pos)))
      | Op.Div => ok (done (core.result.Result.Ok (left, pos)))
    | Token.LParen => ok (done (core.result.Result.Ok (left, pos)))
    | Token.RParen => ok (done (core.result.Result.Ok (left, pos)))
  else ok (done (core.result.Result.Ok (left, pos)))
partial_fixpoint

/-- [infix_calc::parse_expr]:
    Source: 'src/lib.rs', lines 131:0-151:1 -/
def parse_expr
  (tokens : Slice Token) (pos : Std.Usize) :
  Result (core.result.Result (Expr × Std.Usize) ParseError)
  := do
  let r ← parse_term tokens pos
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let (left, pos1) := val
    parse_expr_loop tokens left pos1
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      (Expr × Std.Usize) (core.convert.FromSame ParseError) residual
partial_fixpoint

/-- [infix_calc::parse_term]: loop 0:
    Source: 'src/lib.rs', lines 1:0-175:1 -/
@[rust_loop]
def parse_term_loop
  (tokens : Slice Token) (left : Expr) (pos : Std.Usize) :
  Result (core.result.Result (Expr × Std.Usize) ParseError)
  := do
  loop
    (fun (left1, pos1) => parse_term_loop.body tokens left1 pos1)
    (left, pos)
partial_fixpoint

/-- [infix_calc::parse_term]: loop body 0:
    Source: 'src/lib.rs', lines 1:0-175:1 -/
@[rust_loop_body]
def parse_term_loop.body
  (tokens : Slice Token) (left : Expr) (pos : Std.Usize) :
  Result (ControlFlow (Expr × Std.Usize) (core.result.Result (Expr ×
    Std.Usize) ParseError))
  := do
  let i := Slice.len tokens
  if pos < i
  then
    let t ← Slice.index_usize tokens pos
    match t with
    | Token.Num _ => ok (done (core.result.Result.Ok (left, pos)))
    | Token.Operator o =>
      match o with
      | Op.Add => ok (done (core.result.Result.Ok (left, pos)))
      | Op.Sub => ok (done (core.result.Result.Ok (left, pos)))
      | Op.Mul =>
        let i1 ← pos + 1#usize
        let r ← parse_factor tokens i1
        let cf ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let (right, next) := val
          ok (cont (Expr.BinOp Op.Mul left right, next))
        | core.ops.control_flow.ControlFlow.Break residual =>
          let r1 ←
            core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
              (Expr × Std.Usize) (core.convert.FromSame ParseError) residual
          ok (done r1)
      | Op.Div =>
        let i1 ← pos + 1#usize
        let r ← parse_factor tokens i1
        let cf ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let (right, next) := val
          ok (cont (Expr.BinOp Op.Div left right, next))
        | core.ops.control_flow.ControlFlow.Break residual =>
          let r1 ←
            core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
              (Expr × Std.Usize) (core.convert.FromSame ParseError) residual
          ok (done r1)
    | Token.LParen => ok (done (core.result.Result.Ok (left, pos)))
    | Token.RParen => ok (done (core.result.Result.Ok (left, pos)))
  else ok (done (core.result.Result.Ok (left, pos)))
partial_fixpoint

/-- [infix_calc::parse_term]:
    Source: 'src/lib.rs', lines 155:0-175:1 -/
def parse_term
  (tokens : Slice Token) (pos : Std.Usize) :
  Result (core.result.Result (Expr × Std.Usize) ParseError)
  := do
  let r ← parse_factor tokens pos
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let (left, pos1) := val
    parse_term_loop tokens left pos1
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      (Expr × Std.Usize) (core.convert.FromSame ParseError) residual
partial_fixpoint

/-- [infix_calc::parse_factor]:
    Source: 'src/lib.rs', lines 178:0-197:1 -/
def parse_factor
  (tokens : Slice Token) (pos : Std.Usize) :
  Result (core.result.Result (Expr × Std.Usize) ParseError)
  := do
  let i := Slice.len tokens
  if pos >= i
  then ok (core.result.Result.Err ParseError.UnexpectedEnd)
  else
    let t ← Slice.index_usize tokens pos
    match t with
    | Token.Num n =>
      let i1 ← pos + 1#usize
      ok (core.result.Result.Ok (Expr.Num n, i1))
    | Token.Operator _ =>
      ok (core.result.Result.Err ParseError.UnexpectedToken)
    | Token.LParen =>
      let i1 ← pos + 1#usize
      let r ← parse_expr tokens i1
      let cf ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        let (expr, next) := val
        let i2 := Slice.len tokens
        if next >= i2
        then ok (core.result.Result.Err ParseError.UnexpectedEnd)
        else
          let t1 ← Slice.index_usize tokens next
          match t1 with
          | Token.Num _ =>
            ok (core.result.Result.Err ParseError.UnexpectedToken)
          | Token.Operator _ =>
            ok (core.result.Result.Err ParseError.UnexpectedToken)
          | Token.LParen =>
            ok (core.result.Result.Err ParseError.UnexpectedToken)
          | Token.RParen =>
            let i3 ← next + 1#usize
            ok (core.result.Result.Ok (expr, i3))
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          (Expr × Std.Usize) (core.convert.FromSame ParseError) residual
    | Token.RParen => ok (core.result.Result.Err ParseError.UnexpectedToken)
partial_fixpoint

end

/-- [infix_calc::parse]:
    Source: 'src/lib.rs', lines 200:0-206:1 -/
def parse
  (tokens : Slice Token) : Result (core.result.Result Expr ParseError) := do
  let r ← parse_expr tokens 0#usize
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let (expr, pos) := val
    let i := Slice.len tokens
    if pos != i
    then ok (core.result.Result.Err ParseError.TrailingTokens)
    else ok (core.result.Result.Ok expr)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      Expr (core.convert.FromSame ParseError) residual

/-- [infix_calc::eval]:
    Source: 'src/lib.rs', lines 213:0-233:1 -/
def eval (expr : Expr) : Result (core.result.Result Std.I64 EvalError) := do
  match expr with
  | Expr.Num n => ok (core.result.Result.Ok n)
  | Expr.BinOp op left right =>
    let r ← eval left
    let cf ←
      core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let r1 ← eval right
      let cf1 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        match op with
        | Op.Add =>
          let o ← lift (I64.checked_add val val1)
          core.option.Option.ok_or o EvalError.Overflow
        | Op.Sub =>
          let o ← lift (I64.checked_sub val val1)
          core.option.Option.ok_or o EvalError.Overflow
        | Op.Mul =>
          let o ← lift (I64.checked_mul val val1)
          core.option.Option.ok_or o EvalError.Overflow
        | Op.Div =>
          if val1 = 0#i64
          then ok (core.result.Result.Err EvalError.DivisionByZero)
          else
            let o ← lift (I64.checked_div val val1)
            core.option.Option.ok_or o EvalError.Overflow
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          Std.I64 (core.convert.FromSame EvalError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Std.I64 (core.convert.FromSame EvalError) residual
partial_fixpoint

end infix_calc
