-- [GENERATED BY AENEAS]
-- This file was automatically generated by Aeneas from the Rust crate `rpn_calc`.
-- It contains the function definitions translated from Rust to pure Lean.
--
-- KEY CONCEPTS IN THIS FILE:
--
-- 1. Stack operations (push, pop, peek, len) become pattern-matching functions
--    on the Stack inductive type.
--
-- 2. The while loop in `evaluate` becomes a recursive function annotated with
--    @[rust_loop] and declared via `partial_fixpoint`. This is how Aeneas
--    handles loops: it translates them to tail-recursive functions with a
--    fuel-based termination argument.
--
-- 3. Each function returns `Result T` — Aeneas's wrapper that captures panics
--    and overflow. When the Rust function itself returns `Result<A, B>`, you
--    get `Result (core.result.Result A B)`.
--
-- DO NOT EDIT THIS FILE — it will be overwritten when you re-run Aeneas.

import Aeneas
import RpnCalc.Types

open Aeneas Aeneas.Std Result
open rpn_calc

namespace rpn_calc

/-- Translation of `Stack::new`. -/
def Stack.new : Result Stack :=
  ok Stack.Empty

/-- Translation of `Stack::push`. -/
def Stack.push_ (self : Stack) (val : I64) : Result Stack :=
  ok (Stack.Push val self)

/-- Translation of `Stack::pop`. -/
def Stack.pop_ (self : Stack) : Result (core.result.Result (I64 × Stack) EvalError) :=
  match self with
  | Stack.Push val rest => ok (.ok (val, rest))
  | Stack.Empty => ok (.err EvalError.StackUnderflow)

/-- Translation of `Stack::peek`. -/
def Stack.peek_ (self : Stack) : Result (core.result.Result I64 EvalError) :=
  match self with
  | Stack.Push val _ => ok (.ok val)
  | Stack.Empty => ok (.err EvalError.StackUnderflow)

/-- Translation of `Stack::len`. -/
def Stack.len_ (self : Stack) : Result Usize :=
  match self with
  | Stack.Empty => ok (0 : Usize)
  | Stack.Push _ rest => do
    let rest_len ← Stack.len_ rest
    rest_len + (1 : Usize)

/-- Translation of `Stack::is_empty`. -/
def Stack.is_empty_ (self : Stack) : Result Bool :=
  match self with
  | Stack.Empty => ok true
  | Stack.Push _ _ => ok false

/-- Translation of `parse_number`.
    The while loop becomes a @[rust_loop] recursive function. -/
@[rust_loop]
def parse_number_loop (bytes : Slice U8) (acc : I64) (i : Usize) :
    Result (core.result.Result Token EvalError) := do
  if i < bytes.len then do
    let c ← bytes.index i
    if c < 48 ∨ c > 57 then    -- b'0' = 48, b'9' = 57
      ok (.err EvalError.InvalidToken)
    else do
      let c_minus_48 ← c - (48 : U8)
      let digit ← U8.toI64 c_minus_48
      let prod ← acc * (10 : I64)
      let acc' ← prod + digit
      let i' ← i + (1 : Usize)
      parse_number_loop bytes acc' i'
  else
    ok (.ok (Token.Num acc))
termination_by (bytes.val.size - i.val)
decreasing_by sorry

def parse_number (bytes : Slice U8) :
    Result (core.result.Result Token EvalError) := do
  if bytes.len = (0 : Usize) then
    ok (.err EvalError.InvalidToken)
  else
    parse_number_loop bytes (0 : I64) (0 : Usize)

/-- Translation of `tokenize_word`. -/
def tokenize_word (word : Slice U8) :
    Result (core.result.Result Token EvalError) := do
  if word.len = (1 : Usize) then do
    let c ← word.index (0 : Usize)
    if c = 43 then ok (.ok Token.Plus)           -- b'+'
    else if c = 45 then ok (.ok Token.Minus)      -- b'-'
    else if c = 42 then ok (.ok Token.Mul)         -- b'*'
    else if c = 47 then ok (.ok Token.Div)         -- b'/'
    else if 48 ≤ c ∧ c ≤ 57 then do               -- b'0'..=b'9'
      let c_minus_48 ← c - (48 : U8)
      let n ← U8.toI64 c_minus_48
      ok (.ok (Token.Num n))
    else
      ok (.err EvalError.InvalidToken)
  else
    parse_number word

/-- Translation of `apply_binop`. -/
def apply_binop (op : Token) (a : I64) (b : I64) :
    Result (core.result.Result I64 EvalError) :=
  match op with
  | Token.Plus => do
    let r ← a + b
    ok (.ok r)
  | Token.Minus => do
    let r ← a - b
    ok (.ok r)
  | Token.Mul => do
    let r ← a * b
    ok (.ok r)
  | Token.Div =>
    if b = (0 : I64) then
      ok (.err EvalError.DivisionByZero)
    else do
      let r ← a / b
      ok (.ok r)
  | Token.Num _ =>
    ok (.err EvalError.InvalidToken)

/-- Translation of `eval_step`. -/
def eval_step (stack : Stack) (token : Token) :
    Result (core.result.Result Stack EvalError) :=
  match token with
  | Token.Num n => do
    let s' ← Stack.push_ stack n
    ok (.ok s')
  | op => do
    let pop1 ← Stack.pop_ stack
    match pop1 with
    | .err e => ok (.err e)
    | .ok (b, stack1) => do
      let pop2 ← Stack.pop_ stack1
      match pop2 with
      | .err e => ok (.err e)
      | .ok (a, stack2) => do
        let binop_result ← apply_binop op a b
        match binop_result with
        | .err e => ok (.err e)
        | .ok result => do
          let s' ← Stack.push_ stack2 result
          ok (.ok s')

/-- Translation of `evaluate`.
    The while loop becomes a @[rust_loop] recursive function. -/
@[rust_loop]
def evaluate_loop (tokens : Slice Token) (stack : Stack) (i : Usize) :
    Result (core.result.Result I64 EvalError) := do
  if i < tokens.len then do
    let token ← tokens.index i
    let step_result ← eval_step stack token
    match step_result with
    | .err e => ok (.err e)
    | .ok stack' => do
      let i' ← i + (1 : Usize)
      evaluate_loop tokens stack' i'
  else
    match stack with
    | Stack.Push val Stack.Empty => ok (.ok val)
    | Stack.Empty => ok (.err EvalError.StackUnderflow)
    | _ => ok (.err EvalError.TooManyValues)
termination_by (tokens.val.size - i.val)
decreasing_by sorry

def evaluate (tokens : Slice Token) :
    Result (core.result.Result I64 EvalError) := do
  let stack ← Stack.new
  evaluate_loop tokens stack (0 : Usize)

end rpn_calc
