-- [GENERATED BY AENEAS]
-- This file was automatically generated by Aeneas from the Rust crate `rpn_calc`.
-- It contains the type definitions extracted from the Rust source.
--
-- The Rust enums Token, EvalError, and Stack become Lean inductive types.
-- Notice how each Rust enum variant becomes a Lean constructor.
--
-- DO NOT EDIT THIS FILE — it will be overwritten when you re-run Aeneas.

import Aeneas
open Aeneas Aeneas.Std

namespace rpn_calc

/-- Translation of Rust `Token` enum.
    Each variant maps directly to a constructor. -/
inductive Token where
  | Num : I64 -> Token
  | Plus : Token
  | Minus : Token
  | Mul : Token
  | Div : Token
deriving Repr, BEq

/-- Translation of Rust `EvalError` enum. -/
inductive EvalError where
  | DivisionByZero : EvalError
  | StackUnderflow : EvalError
  | TooManyValues : EvalError
  | InvalidToken : EvalError
deriving Repr, BEq

/-- Translation of Rust `Stack` enum.
    The functional linked list becomes a recursive inductive type.
    Note: Rust's `Box<Stack>` disappears — Lean handles recursion natively. -/
inductive Stack where
  | Empty : Stack
  | Push : I64 -> Stack -> Stack
deriving Repr, BEq

end rpn_calc
